const jsonEmoji7 = [
  {
    type: 7,
    selected: false,
    image: '231a.png',
    code_decimal: '&#8986;',
    title: ':watch:',
    description: 'WATCH',
  },
  {
    type: 7,
    selected: false,
    image: '1f4f1.png',
    code_decimal: '&#128241;',
    title: ':iphone:',
    description: 'IPHONE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4f2.png',
    code_decimal: '&#128242;',
    title: ':calling:',
    description: 'CALLING',
  },
  {
    type: 7,
    selected: false,
    image: '1f4bb.png',
    code_decimal: '&#128187;',
    title: ':computer:',
    description: 'COMPUTER',
  },
  {
    type: 7,
    selected: false,
    image: '1f5a5.png',
    code_decimal: '&#128421;',
    title: ':desktop:',
    description: 'DESKTOP',
  },
  {
    type: 7,
    selected: false,
    image: '1f5ae.png',
    code_decimal: '&#128430;',
    title: ':keyboard:',
    description: 'KEYBOARD',
  },
  {
    type: 7,
    selected: false,
    image: '1f5b2.png',
    code_decimal: '&#128434;',
    title: ':trackball:',
    description: 'TRACKBALL',
  },
  {
    type: 7,
    selected: false,
    image: '1f5a8.png',
    code_decimal: '&#128424;',
    title: ':printer:',
    description: 'PRINTER',
  },
  {
    type: 7,
    selected: false,
    image: '23f0.png',
    code_decimal: '&#9200;',
    title: ':alarm_clock:',
    description: 'ALARM_CLOCK',
  },
  {
    type: 7,
    selected: false,
    image: '1f570.png',
    code_decimal: '&#128368;',
    title: ':clock:',
    description: 'CLOCK',
  },
  {
    type: 7,
    selected: false,
    image: '23f3.png',
    code_decimal: '&#9203;',
    title: ':hourglass_flowing_sand:',
    description: 'HOURGLASS_FLOWING_SAND',
  },
  {
    type: 7,
    selected: false,
    image: '231b.png',
    code_decimal: '&#8987;',
    title: ':hourglass:',
    description: 'HOURGLASS',
  },
  {
    type: 7,
    selected: false,
    image: '1f4f7.png',
    code_decimal: '&#128247;',
    title: ':camera:',
    description: 'CAMERA',
  },
  {
    type: 7,
    selected: false,
    image: '1f4f8.png',
    code_decimal: '&#128248;',
    title: ':camera_with_flash:',
    description: 'CAMERA_WITH_FLASH',
  },
  {
    type: 7,
    selected: false,
    image: '1f4f9.png',
    code_decimal: '&#128249;',
    title: ':video_camera:',
    description: 'VIDEO_CAMERA',
  },
  {
    type: 7,
    selected: false,
    image: '1f3a5.png',
    code_decimal: '&#127909;',
    title: ':movie_camera:',
    description: 'MOVIE_CAMERA',
  },
  {
    type: 7,
    selected: false,
    image: '1f4fd.png',
    code_decimal: '&#128253;',
    title: ':projector:',
    description: 'PROJECTOR',
  },
  {
    type: 7,
    selected: false,
    image: '1f4fa.png',
    code_decimal: '&#128250;',
    title: ':tv:',
    description: 'TV',
  },
  {
    type: 7,
    selected: false,
    image: '1f399.png',
    code_decimal: '&#127897;',
    title: ':microphone2:',
    description: 'MICROPHONE2',
  },
  {
    type: 7,
    selected: false,
    image: '1f39a.png',
    code_decimal: '&#127898;',
    title: ':level_slider:',
    description: 'LEVEL_SLIDER',
  },
  {
    type: 7,
    selected: false,
    image: '1f39b.png',
    code_decimal: '&#127899;',
    title: ':control_knobs:',
    description: 'CONTROL_KNOBS',
  },
  {
    type: 7,
    selected: false,
    image: '1f4fb.png',
    code_decimal: '&#128251;',
    title: ':radio:',
    description: 'RADIO',
  },
  {
    type: 7,
    selected: false,
    image: '1f4df.png',
    code_decimal: '&#128223;',
    title: ':pager:',
    description: 'PAGER',
  },
  {
    type: 7,
    selected: false,
    image: '1f579.png',
    code_decimal: '&#128377;',
    title: ':joystick:',
    description: 'JOYSTICK',
  },
  {
    type: 7,
    selected: false,
    image: '1f4de.png',
    code_decimal: '&#128222;',
    title: ':telephone_receiver:',
    description: 'TELEPHONE_RECEIVER',
  },
  {
    type: 7,
    selected: false,
    image: '260e.png',
    code_decimal: '&#9742;',
    title: ':telephone:',
    description: 'TELEPHONE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4e0.png',
    code_decimal: '&#128224;',
    title: ':fax:',
    description: 'FAX',
  },
  {
    type: 7,
    selected: false,
    image: '1f4bd.png',
    code_decimal: '&#128189;',
    title: ':minidisc:',
    description: 'MINIDISC',
  },
  {
    type: 7,
    selected: false,
    image: '1f4be.png',
    code_decimal: '&#128190;',
    title: ':floppy_disk:',
    description: 'FLOPPY_DISK',
  },
  {
    type: 7,
    selected: false,
    image: '1f4bf.png',
    code_decimal: '&#128191;',
    title: ':cd:',
    description: 'CD',
  },
  {
    type: 7,
    selected: false,
    image: '1f4c0.png',
    code_decimal: '&#128192;',
    title: ':dvd:',
    description: 'DVD',
  },
  {
    type: 7,
    selected: false,
    image: '1f4fc.png',
    code_decimal: '&#128252;',
    title: ':vhs:',
    description: 'VHS',
  },
  {
    type: 7,
    selected: false,
    image: '1f50b.png',
    code_decimal: '&#128267;',
    title: ':battery:',
    description: 'BATTERY',
  },
  {
    type: 7,
    selected: false,
    image: '1f50c.png',
    code_decimal: '&#128268;',
    title: ':electric_plug:',
    description: 'ELECTRIC_PLUG',
  },
  {
    type: 7,
    selected: false,
    image: '1f4a1.png',
    code_decimal: '&#128161;',
    title: ':bulb:',
    description: 'BULB',
  },
  {
    type: 7,
    selected: false,
    image: '1f526.png',
    code_decimal: '&#128294;',
    title: ':flashlight:',
    description: 'FLASHLIGHT',
  },
  {
    type: 7,
    selected: false,
    image: '1f56f.png',
    code_decimal: '&#128367;',
    title: ':candle:',
    description: 'CANDLE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4e1.png',
    code_decimal: '&#128225;',
    title: ':satellite:',
    description: 'SATELLITE',
  },
  {
    type: 7,
    selected: false,
    image: '1f6f0.png',
    code_decimal: '&#128752;',
    title: ':satellite_orbital:',
    description: 'SATELLITE_ORBITAL',
  },
  {
    type: 7,
    selected: false,
    image: '1f4b3.png',
    code_decimal: '&#128179;',
    title: ':credit_card:',
    description: 'CREDIT_CARD',
  },
  {
    type: 7,
    selected: false,
    image: '1f4b8.png',
    code_decimal: '&#128184;',
    title: ':money_with_wings:',
    description: 'MONEY_WITH_WINGS',
  },
  {
    type: 7,
    selected: false,
    image: '1f4b0.png',
    code_decimal: '&#128176;',
    title: ':moneybag:',
    description: 'MONEYBAG',
  },
  {
    type: 7,
    selected: false,
    image: '1f48e.png',
    code_decimal: '&#128142;',
    title: ':gem:',
    description: 'GEM',
  },
  {
    type: 7,
    selected: false,
    image: '1f302.png',
    code_decimal: '&#127746;',
    title: ':closed_umbrella:',
    description: 'CLOSED_UMBRELLA',
  },
  {
    type: 7,
    selected: false,
    image: '1f45d.png',
    code_decimal: '&#128093;',
    title: ':pouch:',
    description: 'POUCH',
  },
  {
    type: 7,
    selected: false,
    image: '1f45b.png',
    code_decimal: '&#128091;',
    title: ':purse:',
    description: 'PURSE',
  },
  {
    type: 7,
    selected: false,
    image: '1f45c.png',
    code_decimal: '&#128092;',
    title: ':handbag:',
    description: 'HANDBAG',
  },
  {
    type: 7,
    selected: false,
    image: '1f4bc.png',
    code_decimal: '&#128188;',
    title: ':briefcase:',
    description: 'BRIEFCASE',
  },
  {
    type: 7,
    selected: false,
    image: '1f392.png',
    code_decimal: '&#127890;',
    title: ':school_satchel:',
    description: 'SCHOOL_SATCHEL',
  },
  {
    type: 7,
    selected: false,
    image: '1f484.png',
    code_decimal: '&#128132;',
    title: ':lipstick:',
    description: 'LIPSTICK',
  },
  {
    type: 7,
    selected: false,
    image: '1f453.png',
    code_decimal: '&#128083;',
    title: ':eyeglasses:',
    description: 'EYEGLASSES',
  },
  {
    type: 7,
    selected: false,
    image: '1f576.png',
    code_decimal: '&#128374;',
    title: ':dark_sunglasses:',
    description: 'DARK_SUNGLASSES',
  },
  {
    type: 7,
    selected: false,
    image: '1f452.png',
    code_decimal: '&#128082;',
    title: ':womans_hat:',
    description: 'WOMANS_HAT',
  },
  {
    type: 7,
    selected: false,
    image: '1f461.png',
    code_decimal: '&#128097;',
    title: ':sandal:',
    description: 'SANDAL',
  },
  {
    type: 7,
    selected: false,
    image: '1f460.png',
    code_decimal: '&#128096;',
    title: ':high_heel:',
    description: 'HIGH_HEEL',
  },
  {
    type: 7,
    selected: false,
    image: '1f462.png',
    code_decimal: '&#128098;',
    title: ':boot:',
    description: 'BOOT',
  },
  {
    type: 7,
    selected: false,
    image: '1f45e.png',
    code_decimal: '&#128094;',
    title: ':mans_shoe:',
    description: 'MANS_SHOE',
  },
  {
    type: 7,
    selected: false,
    image: '1f45f.png',
    code_decimal: '&#128095;',
    title: ':athletic_shoe:',
    description: 'ATHLETIC_SHOE',
  },
  {
    type: 7,
    selected: false,
    image: '1f459.png',
    code_decimal: '&#128089;',
    title: ':bikini:',
    description: 'BIKINI',
  },
  {
    type: 7,
    selected: false,
    image: '1f457.png',
    code_decimal: '&#128087;',
    title: ':dress:',
    description: 'DRESS',
  },
  {
    type: 7,
    selected: false,
    image: '1f458.png',
    code_decimal: '&#128088;',
    title: ':kimono:',
    description: 'KIMONO',
  },
  {
    type: 7,
    selected: false,
    image: '1f45a.png',
    code_decimal: '&#128090;',
    title: ':womans_clothes:',
    description: 'WOMANS_CLOTHES',
  },
  {
    type: 7,
    selected: false,
    image: '1f455.png',
    code_decimal: '&#128085;',
    title: ':shirt:',
    description: 'SHIRT',
  },
  {
    type: 7,
    selected: false,
    image: '1f454.png',
    code_decimal: '&#128084;',
    title: ':necktie:',
    description: 'NECKTIE',
  },
  {
    type: 7,
    selected: false,
    image: '1f456.png',
    code_decimal: '&#128086;',
    title: ':jeans:',
    description: 'JEANS',
  },
  {
    type: 7,
    selected: false,
    image: '1f6aa.png',
    code_decimal: '&#128682;',
    title: ':door:',
    description: 'DOOR',
  },
  {
    type: 7,
    selected: false,
    image: '1f6bf.png',
    code_decimal: '&#128703;',
    title: ':shower:',
    description: 'SHOWER',
  },
  {
    type: 7,
    selected: false,
    image: '1f6c1.png',
    code_decimal: '&#128705;',
    title: ':bathtub:',
    description: 'BATHTUB',
  },
  {
    type: 7,
    selected: false,
    image: '1f6bd.png',
    code_decimal: '&#128701;',
    title: ':toilet:',
    description: 'TOILET',
  },
  {
    type: 7,
    selected: false,
    image: '1f488.png',
    code_decimal: '&#128136;',
    title: ':barber:',
    description: 'BARBER',
  },
  {
    type: 7,
    selected: false,
    image: '1f489.png',
    code_decimal: '&#128137;',
    title: ':syringe:',
    description: 'SYRINGE',
  },
  {
    type: 7,
    selected: false,
    image: '1f48a.png',
    code_decimal: '&#128138;',
    title: ':pill:',
    description: 'PILL',
  },
  {
    type: 7,
    selected: false,
    image: '1f52c.png',
    code_decimal: '&#128300;',
    title: ':microscope:',
    description: 'MICROSCOPE',
  },
  {
    type: 7,
    selected: false,
    image: '1f52d.png',
    code_decimal: '&#128301;',
    title: ':telescope:',
    description: 'TELESCOPE',
  },
  {
    type: 7,
    selected: false,
    image: '1f52e.png',
    code_decimal: '&#128302;',
    title: ':crystal_ball:',
    description: 'CRYSTAL_BALL',
  },
  {
    type: 7,
    selected: false,
    image: '1f527.png',
    code_decimal: '&#128295;',
    title: ':wrench:',
    description: 'WRENCH',
  },
  {
    type: 7,
    selected: false,
    image: '1f52a.png',
    code_decimal: '&#128298;',
    title: ':knife:',
    description: 'KNIFE',
  },
  {
    type: 7,
    selected: false,
    image: '1f5e1.png',
    code_decimal: '&#128481;',
    title: ':dagger:',
    description: 'DAGGER',
  },
  {
    type: 7,
    selected: false,
    image: '1f529.png',
    code_decimal: '&#128297;',
    title: ':nut_and_bolt:',
    description: 'NUT_AND_BOLT',
  },
  {
    type: 7,
    selected: false,
    image: '1f528.png',
    code_decimal: '&#128296;',
    title: ':hammer:',
    description: 'HAMMER',
  },
  {
    type: 7,
    selected: false,
    image: '1f6e0.png',
    code_decimal: '&#128736;',
    title: ':tools:',
    description: 'TOOLS',
  },
  {
    type: 7,
    selected: false,
    image: '1f6e2.png',
    code_decimal: '&#128738;',
    title: ':oil:',
    description: 'OIL',
  },
  {
    type: 7,
    selected: false,
    image: '1f4a3.png',
    code_decimal: '&#128163;',
    title: ':bomb:',
    description: 'BOMB',
  },
  {
    type: 7,
    selected: false,
    image: '1f6ac.png',
    code_decimal: '&#128684;',
    title: ':smoking:',
    description: 'SMOKING',
  },
  {
    type: 7,
    selected: false,
    image: '1f52b.png',
    code_decimal: '&#128299;',
    title: ':gun:',
    description: 'GUN',
  },
  {
    type: 7,
    selected: false,
    image: '1f516.png',
    code_decimal: '&#128278;',
    title: ':bookmark:',
    description: 'BOOKMARK',
  },
  {
    type: 7,
    selected: false,
    image: '1f4f0.png',
    code_decimal: '&#128240;',
    title: ':newspaper:',
    description: 'NEWSPAPER',
  },
  {
    type: 7,
    selected: false,
    image: '1f5de.png',
    code_decimal: '&#128478;',
    title: ':newspaper2:',
    description: 'NEWSPAPER2',
  },
  {
    type: 7,
    selected: false,
    image: '1f321.png',
    code_decimal: '&#127777;',
    title: ':thermometer:',
    description: 'THERMOMETER',
  },
  {
    type: 7,
    selected: false,
    image: '1f3f7.png',
    code_decimal: '&#127991;',
    title: ':label:',
    description: 'LABEL',
  },
  {
    type: 7,
    selected: false,
    image: '1f511.png',
    code_decimal: '&#128273;',
    title: ':key:',
    description: 'KEY',
  },
  {
    type: 7,
    selected: false,
    image: '1f5dd.png',
    code_decimal: '&#128477;',
    title: ':key2:',
    description: 'KEY2',
  },
  {
    type: 7,
    selected: false,
    image: '2709.png',
    code_decimal: '&#9993;',
    title: ':envelope:',
    description: 'ENVELOPE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4e9.png',
    code_decimal: '&#128233;',
    title: ':envelope_with_arrow:',
    description: 'ENVELOPE_WITH_ARROW',
  },
  {
    type: 7,
    selected: false,
    image: '1f4e8.png',
    code_decimal: '&#128232;',
    title: ':incoming_envelope:',
    description: 'INCOMING_ENVELOPE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4e7.png',
    code_decimal: '&#128231;',
    title: ':email:',
    description: 'EMAIL',
  },
  {
    type: 7,
    selected: false,
    image: '1f4e5.png',
    code_decimal: '&#128229;',
    title: ':inbox_tray:',
    description: 'INBOX_TRAY',
  },
  {
    type: 7,
    selected: false,
    image: '1f4e4.png',
    code_decimal: '&#128228;',
    title: ':outbox_tray:',
    description: 'OUTBOX_TRAY',
  },
  {
    type: 7,
    selected: false,
    image: '1f4e6.png',
    code_decimal: '&#128230;',
    title: ':package:',
    description: 'PACKAGE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4ef.png',
    code_decimal: '&#128239;',
    title: ':postal_horn:',
    description: 'POSTAL_HORN',
  },
  {
    type: 7,
    selected: false,
    image: '1f4ee.png',
    code_decimal: '&#128238;',
    title: ':postbox:',
    description: 'POSTBOX',
  },
  {
    type: 7,
    selected: false,
    image: '1f4ea.png',
    code_decimal: '&#128234;',
    title: ':mailbox_closed:',
    description: 'MAILBOX_CLOSED',
  },
  {
    type: 7,
    selected: false,
    image: '1f4eb.png',
    code_decimal: '&#128235;',
    title: ':mailbox:',
    description: 'MAILBOX',
  },
  {
    type: 7,
    selected: false,
    image: '1f4ed.png',
    code_decimal: '&#128237;',
    title: ':mailbox_with_no_mail:',
    description: 'MAILBOX_WITH_NO_MAIL',
  },
  {
    type: 7,
    selected: false,
    image: '1f4ec.png',
    code_decimal: '&#128236;',
    title: ':mailbox_with_mail:',
    description: 'MAILBOX_WITH_MAIL',
  },
  {
    type: 7,
    selected: false,
    image: '1f4c4.png',
    code_decimal: '&#128196;',
    title: ':page_facing_up:',
    description: 'PAGE_FACING_UP',
  },
  {
    type: 7,
    selected: false,
    image: '1f4c3.png',
    code_decimal: '&#128195;',
    title: ':page_with_cHaloContants.PATH_IMAGE_EMOJI:',
    description: 'PAGE_WITH_CURL',
  },
  {
    type: 7,
    selected: false,
    image: '1f4d1.png',
    code_decimal: '&#128209;',
    title: ':bookmark_tabs:',
    description: 'BOOKMARK_TABS',
  },
  {
    type: 7,
    selected: false,
    image: '1f5d1.png',
    code_decimal: '&#128465;',
    title: ':wastebasket:',
    description: 'WASTEBASKET',
  },
  {
    type: 7,
    selected: false,
    image: '1f5d2.png',
    code_decimal: '&#128466;',
    title: ':notepad_spiral:',
    description: 'NOTEPAD_SPIRAL',
  },
  {
    type: 7,
    selected: false,
    image: '1f4c8.png',
    code_decimal: '&#128200;',
    title: ':chart_with_upwards_trend:',
    description: 'CHART_WITH_UPWARDS_TREND',
  },
  {
    type: 7,
    selected: false,
    image: '1f4c9.png',
    code_decimal: '&#128201;',
    title: ':chart_with_downwards_trend:',
    description: 'CHART_WITH_DOWNWARDS_TREND',
  },
  {
    type: 7,
    selected: false,
    image: '1f4ca.png',
    code_decimal: '&#128202;',
    title: ':bar_chart:',
    description: 'BAR_CHART',
  },
  {
    type: 7,
    selected: false,
    image: '1f4c5.png',
    code_decimal: '&#128197;',
    title: ':date:',
    description: 'DATE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4c6.png',
    code_decimal: '&#128198;',
    title: ':calendar:',
    description: 'CALENDAR',
  },
  {
    type: 7,
    selected: false,
    image: '1f5d3.png',
    code_decimal: '&#128467;',
    title: ':calendar_spiral:',
    description: 'CALENDAR_SPIRAL',
  },
  {
    type: 7,
    selected: false,
    image: '1f5f3.png',
    code_decimal: '&#128499;',
    title: ':ballot_box:',
    description: 'BALLOT_BOX',
  },
  {
    type: 7,
    selected: false,
    image: '1f505.png',
    code_decimal: '&#128261;',
    title: ':low_brightness:',
    description: 'LOW_BRIGHTNESS',
  },
  {
    type: 7,
    selected: false,
    image: '1f506.png',
    code_decimal: '&#128262;',
    title: ':high_brightness:',
    description: 'HIGH_BRIGHTNESS',
  },
  {
    type: 7,
    selected: false,
    image: '1f5dc.png',
    code_decimal: '&#128476;',
    title: ':compression:',
    description: 'COMPRESSION',
  },
  {
    type: 7,
    selected: false,
    image: '1f5bc.png',
    code_decimal: '&#128444;',
    title: ':frame_photo:',
    description: 'FRAME_PHOTO',
  },
  {
    type: 7,
    selected: false,
    image: '1f4dc.png',
    code_decimal: '&#128220;',
    title: ':scroll:',
    description: 'SCROLL',
  },
  {
    type: 7,
    selected: false,
    image: '1f4cb.png',
    code_decimal: '&#128203;',
    title: ':clipboard:',
    description: 'CLIPBOARD',
  },
  {
    type: 7,
    selected: false,
    image: '1f4d6.png',
    code_decimal: '&#128214;',
    title: ':book:',
    description: 'BOOK',
  },
  {
    type: 7,
    selected: false,
    image: '1f4d3.png',
    code_decimal: '&#128211;',
    title: ':notebook:',
    description: 'NOTEBOOK',
  },
  {
    type: 7,
    selected: false,
    image: '1f4d4.png',
    code_decimal: '&#128212;',
    title: ':notebook_with_decorative_cover:',
    description: 'NOTEBOOK_WITH_DECORATIVE_COVER',
  },
  {
    type: 7,
    selected: false,
    image: '1f4d2.png',
    code_decimal: '&#128210;',
    title: ':ledger:',
    description: 'LEDGER',
  },
  {
    type: 7,
    selected: false,
    image: '1f4d5.png',
    code_decimal: '&#128213;',
    title: ':closed_book:',
    description: 'CLOSED_BOOK',
  },
  {
    type: 7,
    selected: false,
    image: '1f4d7.png',
    code_decimal: '&#128215;',
    title: ':green_book:',
    description: 'GREEN_BOOK',
  },
  {
    type: 7,
    selected: false,
    image: '1f4d8.png',
    code_decimal: '&#128216;',
    title: ':blue_book:',
    description: 'BLUE_BOOK',
  },
  {
    type: 7,
    selected: false,
    image: '1f4d9.png',
    code_decimal: '&#128217;',
    title: ':orange_book:',
    description: 'ORANGE_BOOK',
  },
  {
    type: 7,
    selected: false,
    image: '1f4da.png',
    code_decimal: '&#128218;',
    title: ':books:',
    description: 'BOOKS',
  },
  {
    type: 7,
    selected: false,
    image: '1f4c7.png',
    code_decimal: '&#128199;',
    title: ':card_index:',
    description: 'CARD_INDEX',
  },
  {
    type: 7,
    selected: false,
    image: '1f5c2.png',
    code_decimal: '&#128450;',
    title: ':dividers:',
    description: 'DIVIDERS',
  },
  {
    type: 7,
    selected: false,
    image: '1f5c3.png',
    code_decimal: '&#128451;',
    title: ':card_box:',
    description: 'CARD_BOX',
  },
  {
    type: 7,
    selected: false,
    image: '1f517.png',
    code_decimal: '&#128279;',
    title: ':link:',
    description: 'LINK',
  },
  {
    type: 7,
    selected: false,
    image: '1f4ce.png',
    code_decimal: '&#128206;',
    title: ':paperclip:',
    description: 'PAPERCLIP',
  },
  {
    type: 7,
    selected: false,
    image: '1f587.png',
    code_decimal: '&#128391;',
    title: ':paperclips:',
    description: 'PAPERCLIPS',
  },
  {
    type: 7,
    selected: false,
    image: '1f4cc.png',
    code_decimal: '&#128204;',
    title: ':pushpin:',
    description: 'PUSHPIN',
  },
  {
    type: 7,
    selected: false,
    image: '2702.png',
    code_decimal: '&#9986;',
    title: ':scissors:',
    description: 'SCISSORS',
  },
  {
    type: 7,
    selected: false,
    image: '1f4d0.png',
    code_decimal: '&#128208;',
    title: ':triangular_ruler:',
    description: 'TRIANGULAR_RULER',
  },
  {
    type: 7,
    selected: false,
    image: '1f4cd.png',
    code_decimal: '&#128205;',
    title: ':round_pushpin:',
    description: 'ROUND_PUSHPIN',
  },
  {
    type: 7,
    selected: false,
    image: '1f4cf.png',
    code_decimal: '&#128207;',
    title: ':straight_ruler:',
    description: 'STRAIGHT_RULER',
  },
  {
    type: 7,
    selected: false,
    image: '1f6a9.png',
    code_decimal: '&#128681;',
    title: ':triangular_flag_on_post:',
    description: 'TRIANGULAR_FLAG_ON_POST',
  },
  {
    type: 7,
    selected: false,
    image: '1f3f3.png',
    code_decimal: '&#127987;',
    title: ':flag_white:',
    description: 'FLAG_WHITE',
  },
  {
    type: 7,
    selected: false,
    image: '1f3f4.png',
    code_decimal: '&#127988;',
    title: ':flag_black:',
    description: 'FLAG_BLACK',
  },
  {
    type: 7,
    selected: false,
    image: '1f573.png',
    code_decimal: '&#128371;',
    title: ':hole:',
    description: 'HOLE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4c1.png',
    code_decimal: '&#128193;',
    title: ':file_folder:',
    description: 'FILE_FOLDER',
  },
  {
    type: 7,
    selected: false,
    image: '1f4c2.png',
    code_decimal: '&#128194;',
    title: ':open_file_folder:',
    description: 'OPEN_FILE_FOLDER',
  },
  {
    type: 7,
    selected: false,
    image: '1f5c4.png',
    code_decimal: '&#128452;',
    title: ':file_cabinet:',
    description: 'FILE_CABINET',
  },
  {
    type: 7,
    selected: false,
    image: '2712.png',
    code_decimal: '&#10002;',
    title: ':black_nib:',
    description: 'BLACK_NIB',
  },
  {
    type: 7,
    selected: false,
    image: '270f.png',
    code_decimal: '&#9999;',
    title: ':pencil2:',
    description: 'PENCIL2',
  },
  {
    type: 7,
    selected: false,
    image: '1f58a.png',
    code_decimal: '&#128394;',
    title: ':pen_ballpoint:',
    description: 'PEN_BALLPOINT',
  },
  {
    type: 7,
    selected: false,
    image: '1f58b.png',
    code_decimal: '&#128395;',
    title: ':pen_fountain:',
    description: 'PEN_FOUNTAIN',
  },
  {
    type: 7,
    selected: false,
    image: '1f58c.png',
    code_decimal: '&#128396;',
    title: ':paintbrush:',
    description: 'PAINTBRUSH',
  },
  {
    type: 7,
    selected: false,
    image: '1f58d.png',
    code_decimal: '&#128397;',
    title: ':crayon:',
    description: 'CRAYON',
  },
  {
    type: 7,
    selected: false,
    image: '1f4dd.png',
    code_decimal: '&#128221;',
    title: ':pencil:',
    description: 'PENCIL',
  },
  {
    type: 7,
    selected: false,
    image: '1f50f.png',
    code_decimal: '&#128271;',
    title: ':lock_with_ink_pen:',
    description: 'LOCK_WITH_INK_PEN',
  },
  {
    type: 7,
    selected: false,
    image: '1f510.png',
    code_decimal: '&#128272;',
    title: ':closed_lock_with_key:',
    description: 'CLOSED_LOCK_WITH_KEY',
  },
  {
    type: 7,
    selected: false,
    image: '1f512.png',
    code_decimal: '&#128274;',
    title: ':lock:',
    description: 'LOCK',
  },
  {
    type: 7,
    selected: false,
    image: '1f513.png',
    code_decimal: '&#128275;',
    title: ':unlock:',
    description: 'UNLOCK',
  },
  {
    type: 7,
    selected: false,
    image: '1f4e3.png',
    code_decimal: '&#128227;',
    title: ':mega:',
    description: 'MEGA',
  },
  {
    type: 7,
    selected: false,
    image: '1f4e2.png',
    code_decimal: '&#128226;',
    title: ':loudspeaker:',
    description: 'LOUDSPEAKER',
  },
  {
    type: 7,
    selected: false,
    image: '1f508.png',
    code_decimal: '&#128264;',
    title: ':speaker:',
    description: 'SPEAKER',
  },
  {
    type: 7,
    selected: false,
    image: '1f509.png',
    code_decimal: '&#128265;',
    title: ':sound:',
    description: 'SOUND',
  },
  {
    type: 7,
    selected: false,
    image: '1f50a.png',
    code_decimal: '&#128266;',
    title: ':loud_sound:',
    description: 'LOUD_SOUND',
  },
  {
    type: 7,
    selected: false,
    image: '1f507.png',
    code_decimal: '&#128263;',
    title: ':mute:',
    description: 'MUTE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4a4.png',
    code_decimal: '&#128164;',
    title: ':zzz:',
    description: 'ZZZ',
  },
  {
    type: 7,
    selected: false,
    image: '1f514.png',
    code_decimal: '&#128276;',
    title: ':bell:',
    description: 'BELL',
  },
  {
    type: 7,
    selected: false,
    image: '1f515.png',
    code_decimal: '&#128277;',
    title: ':no_bell:',
    description: 'NO_BELL',
  },
  {
    type: 7,
    selected: false,
    image: '1f547.png',
    code_decimal: '&#128327;',
    title: ':cross_heavy:',
    description: 'CROSS_HEAVY',
  },
  {
    type: 7,
    selected: false,
    image: '1f549.png',
    code_decimal: '&#128329;',
    title: ':om_symbol:',
    description: 'OM_SYMBOL',
  },
  {
    type: 7,
    selected: false,
    image: '1f54a.png',
    code_decimal: '&#128330;',
    title: ':dove:',
    description: 'DOVE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4ad.png',
    code_decimal: '&#128173;',
    title: ':thought_balloon:',
    description: 'THOUGHT_BALLOON',
  },
  {
    type: 7,
    selected: false,
    image: '1f4ac.png',
    code_decimal: '&#128172;',
    title: ':speech_balloon:',
    description: 'SPEECH_BALLOON',
  },
  {
    type: 7,
    selected: false,
    image: '1f5ef.png',
    code_decimal: '&#128495;',
    title: ':anger_right:',
    description: 'ANGER_RIGHT',
  },
  {
    type: 7,
    selected: false,
    image: '1f6b8.png',
    code_decimal: '&#128696;',
    title: ':children_crossing:',
    description: 'CHILDREN_CROSSING',
  },
  {
    type: 7,
    selected: false,
    image: '1f6e1.png',
    code_decimal: '&#128737;',
    title: ':shield:',
    description: 'SHIELD',
  },
  {
    type: 7,
    selected: false,
    image: '1f50d.png',
    code_decimal: '&#128269;',
    title: ':mag:',
    description: 'MAG',
  },
  {
    type: 7,
    selected: false,
    image: '1f50e.png',
    code_decimal: '&#128270;',
    title: ':mag_right:',
    description: 'MAG_RIGHT',
  },
  {
    type: 7,
    selected: false,
    image: '1f5e3.png',
    code_decimal: '&#128483;',
    title: ':speaking_head:',
    description: 'SPEAKING_HEAD',
  },
  {
    type: 7,
    selected: false,
    image: '1f6cc.png',
    code_decimal: '&#128716;',
    title: ':sleeping_accommodation:',
    description: 'SLEEPING_ACCOMMODATION',
  },
  {
    type: 7,
    selected: false,
    image: '1f6ab.png',
    code_decimal: '&#128683;',
    title: ':no_entry_sign:',
    description: 'NO_ENTRY_SIGN',
  },
  {
    type: 7,
    selected: false,
    image: '26d4.png',
    code_decimal: '&#9940;',
    title: ':no_entry:',
    description: 'NO_ENTRY',
  },
  {
    type: 7,
    selected: false,
    image: '1f4db.png',
    code_decimal: '&#128219;',
    title: ':name_badge:',
    description: 'NAME_BADGE',
  },
  {
    type: 7,
    selected: false,
    image: '1f6b7.png',
    code_decimal: '&#128695;',
    title: ':no_pedestrians:',
    description: 'NO_PEDESTRIANS',
  },
  {
    type: 7,
    selected: false,
    image: '1f6af.png',
    code_decimal: '&#128687;',
    title: ':do_not_litter:',
    description: 'DO_NOT_LITTER',
  },
  {
    type: 7,
    selected: false,
    image: '1f6b3.png',
    code_decimal: '&#128691;',
    title: ':no_bicycles:',
    description: 'NO_BICYCLES',
  },
  {
    type: 7,
    selected: false,
    image: '1f6b1.png',
    code_decimal: '&#128689;',
    title: ':non_potable_water:',
    description: 'NON_POTABLE_WATER',
  },
  {
    type: 7,
    selected: false,
    image: '1f4f5.png',
    code_decimal: '&#128245;',
    title: ':no_mobile_phones:',
    description: 'NO_MOBILE_PHONES',
  },
  {
    type: 7,
    selected: false,
    image: '1f51e.png',
    code_decimal: '&#128286;',
    title: ':underage:',
    description: 'UNDERAGE',
  },
  {
    type: 7,
    selected: false,
    image: '2747.png',
    code_decimal: '&#10055;',
    title: ':sparkle:',
    description: 'SPARKLE',
  },
  {
    type: 7,
    selected: false,
    image: '2733.png',
    code_decimal: '&#10035;',
    title: ':eight_spoked_asterisk:',
    description: 'EIGHT_SPOKED_ASTERISK',
  },
  {
    type: 7,
    selected: false,
    image: '274e.png',
    code_decimal: '&#10062;',
    title: ':negative_squared_cross_mark:',
    description: 'NEGATIVE_SQUARED_CROSS_MARK',
  },
  {
    type: 7,
    selected: false,
    image: '2705.png',
    code_decimal: '&#9989;',
    title: ':white_check_mark:',
    description: 'WHITE_CHECK_MARK',
  },
  {
    type: 7,
    selected: false,
    image: '2734.png',
    code_decimal: '&#10036;',
    title: ':eight_pointed_black_star:',
    description: 'EIGHT_POINTED_BLACK_STAR',
  },
  {
    type: 7,
    selected: false,
    image: '1f4f3.png',
    code_decimal: '&#128243;',
    title: ':vibration_mode:',
    description: 'VIBRATION_MODE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4f4.png',
    code_decimal: '&#128244;',
    title: ':mobile_phone_off:',
    description: 'MOBILE_PHONE_OFF',
  },
  {
    type: 7,
    selected: false,
    image: '1f19a.png',
    code_decimal: '&#127386;',
    title: ':vs:',
    description: 'VS',
  },
  {
    type: 7,
    selected: false,
    image: '1f170.png',
    code_decimal: '&#127344;',
    title: ':a:',
    description: 'A',
  },
  {
    type: 7,
    selected: false,
    image: '1f171.png',
    code_decimal: '&#127345;',
    title: ':b:',
    description: 'B',
  },
  {
    type: 7,
    selected: false,
    image: '1f18e.png',
    code_decimal: '&#127374;',
    title: ':ab:',
    description: 'AB',
  },
  {
    type: 7,
    selected: false,
    image: '1f191.png',
    code_decimal: '&#127377;',
    title: ':cl:',
    description: 'CL',
  },
  {
    type: 7,
    selected: false,
    image: '1f17e.png',
    code_decimal: '&#127358;',
    title: ':o2:',
    description: 'O2',
  },
  {
    type: 7,
    selected: false,
    image: '1f198.png',
    code_decimal: '&#127384;',
    title: ':sos:',
    description: 'SOS',
  },
  {
    type: 7,
    selected: false,
    image: '1f194.png',
    code_decimal: '&#127380;',
    title: ':id:',
    description: 'ID',
  },
  {
    type: 7,
    selected: false,
    image: '1f17f.png',
    code_decimal: '&#127359;',
    title: ':parking:',
    description: 'PARKING',
  },
  {
    type: 7,
    selected: false,
    image: '1f6be.png',
    code_decimal: '&#128702;',
    title: ':wc:',
    description: 'WC',
  },
  {
    type: 7,
    selected: false,
    image: '1f192.png',
    code_decimal: '&#127378;',
    title: ':cool:',
    description: 'COOL',
  },
  {
    type: 7,
    selected: false,
    image: '1f193.png',
    code_decimal: '&#127379;',
    title: ':free:',
    description: 'FREE',
  },
  {
    type: 7,
    selected: false,
    image: '1f195.png',
    code_decimal: '&#127381;',
    title: ':new:',
    description: 'NEW',
  },
  {
    type: 7,
    selected: false,
    image: '1f196.png',
    code_decimal: '&#127382;',
    title: ':ng:',
    description: 'NG',
  },
  {
    type: 7,
    selected: false,
    image: '1f197.png',
    code_decimal: '&#127383;',
    title: ':ok:',
    description: 'OK',
  },
  {
    type: 7,
    selected: false,
    image: '1f199.png',
    code_decimal: '&#127385;',
    title: ':up:',
    description: 'UP',
  },
  {
    type: 7,
    selected: false,
    image: '1f3e7.png',
    code_decimal: '&#127975;',
    title: ':atm:',
    description: 'ATM',
  },
  {
    type: 7,
    selected: false,
    image: '2648.png',
    code_decimal: '&#9800;',
    title: ':aries:',
    description: 'ARIES',
  },
  {
    type: 7,
    selected: false,
    image: '2649.png',
    code_decimal: '&#9801;',
    title: ':taurus:',
    description: 'TAURUS',
  },
  {
    type: 7,
    selected: false,
    image: '264a.png',
    code_decimal: '&#9802;',
    title: ':gemini:',
    description: 'GEMINI',
  },
  {
    type: 7,
    selected: false,
    image: '264b.png',
    code_decimal: '&#9803;',
    title: ':cancer:',
    description: 'CANCER',
  },
  {
    type: 7,
    selected: false,
    image: '264c.png',
    code_decimal: '&#9804;',
    title: ':leo:',
    description: 'LEO',
  },
  {
    type: 7,
    selected: false,
    image: '264d.png',
    code_decimal: '&#9805;',
    title: ':virgo:',
    description: 'VIRGO',
  },
  {
    type: 7,
    selected: false,
    image: '264e.png',
    code_decimal: '&#9806;',
    title: ':libra:',
    description: 'LIBRA',
  },
  {
    type: 7,
    selected: false,
    image: '264f.png',
    code_decimal: '&#9807;',
    title: ':scorpius:',
    description: 'SCORPIUS',
  },
  {
    type: 7,
    selected: false,
    image: '2650.png',
    code_decimal: '&#9808;',
    title: ':sagittarius:',
    description: 'SAGITTARIUS',
  },
  {
    type: 7,
    selected: false,
    image: '2651.png',
    code_decimal: '&#9809;',
    title: ':capricorn:',
    description: 'CAPRICORN',
  },
  {
    type: 7,
    selected: false,
    image: '2652.png',
    code_decimal: '&#9810;',
    title: ':aquarius:',
    description: 'AQUARIUS',
  },
  {
    type: 7,
    selected: false,
    image: '2653.png',
    code_decimal: '&#9811;',
    title: ':pisces:',
    description: 'PISCES',
  },
  {
    type: 7,
    selected: false,
    image: '1f6bb.png',
    code_decimal: '&#128699;',
    title: ':restroom:',
    description: 'RESTROOM',
  },
  {
    type: 7,
    selected: false,
    image: '1f6b9.png',
    code_decimal: '&#128697;',
    title: ':mens:',
    description: 'MENS',
  },
  {
    type: 7,
    selected: false,
    image: '1f6ba.png',
    code_decimal: '&#128698;',
    title: ':womens:',
    description: 'WOMENS',
  },
  {
    type: 7,
    selected: false,
    image: '1f6bc.png',
    code_decimal: '&#128700;',
    title: ':baby_symbol:',
    description: 'BABY_SYMBOL',
  },
  {
    type: 7,
    selected: false,
    image: '267f.png',
    code_decimal: '&#9855;',
    title: ':wheelchair:',
    description: 'WHEELCHAIR',
  },
  {
    type: 7,
    selected: false,
    image: '1f6b0.png',
    code_decimal: '&#128688;',
    title: ':potable_water:',
    description: 'POTABLE_WATER',
  },
  {
    type: 7,
    selected: false,
    image: '1f6ad.png',
    code_decimal: '&#128685;',
    title: ':no_smoking:',
    description: 'NO_SMOKING',
  },
  {
    type: 7,
    selected: false,
    image: '1f6ae.png',
    code_decimal: '&#128686;',
    title: ':put_litter_in_its_place:',
    description: 'PUT_LITTER_IN_ITS_PLACE',
  },
  {
    type: 7,
    selected: false,
    image: '25b6.png',
    code_decimal: '&#9654;',
    title: ':arrow_forward:',
    description: 'ARROW_FORWARD',
  },
  {
    type: 7,
    selected: false,
    image: '25c0.png',
    code_decimal: '&#9664;',
    title: ':arrow_backward:',
    description: 'ARROW_BACKWARD',
  },
  {
    type: 7,
    selected: false,
    image: '1f53c.png',
    code_decimal: '&#128316;',
    title: ':arrow_up_small:',
    description: 'ARROW_UP_SMALL',
  },
  {
    type: 7,
    selected: false,
    image: '1f53d.png',
    code_decimal: '&#128317;',
    title: ':arrow_down_small:',
    description: 'ARROW_DOWN_SMALL',
  },
  {
    type: 7,
    selected: false,
    image: '23e9.png',
    code_decimal: '&#9193;',
    title: ':fast_forward:',
    description: 'FAST_FORWARD',
  },
  {
    type: 7,
    selected: false,
    image: '23ea.png',
    code_decimal: '&#9194;',
    title: ':rewind:',
    description: 'REWIND',
  },
  {
    type: 7,
    selected: false,
    image: '23eb.png',
    code_decimal: '&#9195;',
    title: ':arrow_double_up:',
    description: 'ARROW_DOUBLE_UP',
  },
  {
    type: 7,
    selected: false,
    image: '23ec.png',
    code_decimal: '&#9196;',
    title: ':arrow_double_down:',
    description: 'ARROW_DOUBLE_DOWN',
  },
  {
    type: 7,
    selected: false,
    image: '27a1.png',
    code_decimal: '&#10145;',
    title: ':arrow_right:',
    description: 'ARROW_RIGHT',
  },
  {
    type: 7,
    selected: false,
    image: '2b05.png',
    code_decimal: '&#11013;',
    title: ':arrow_left:',
    description: 'ARROW_LEFT',
  },
  {
    type: 7,
    selected: false,
    image: '2b06.png',
    code_decimal: '&#11014;',
    title: ':arrow_up:',
    description: 'ARROW_UP',
  },
  {
    type: 7,
    selected: false,
    image: '2b07.png',
    code_decimal: '&#11015;',
    title: ':arrow_down:',
    description: 'ARROW_DOWN',
  },
  {
    type: 7,
    selected: false,
    image: '2197.png',
    code_decimal: '&#8599;',
    title: ':arrow_upper_right:',
    description: 'ARROW_UPPER_RIGHT',
  },
  {
    type: 7,
    selected: false,
    image: '2198.png',
    code_decimal: '&#8600;',
    title: ':arrow_lower_right:',
    description: 'ARROW_LOWER_RIGHT',
  },
  {
    type: 7,
    selected: false,
    image: '2199.png',
    code_decimal: '&#8601;',
    title: ':arrow_lower_left:',
    description: 'ARROW_LOWER_LEFT',
  },
  {
    type: 7,
    selected: false,
    image: '2196.png',
    code_decimal: '&#8598;',
    title: ':arrow_upper_left:',
    description: 'ARROW_UPPER_LEFT',
  },
  {
    type: 7,
    selected: false,
    image: '2195.png',
    code_decimal: '&#8597;',
    title: ':arrow_up_down:',
    description: 'ARROW_UP_DOWN',
  },
  {
    type: 7,
    selected: false,
    image: '2194.png',
    code_decimal: '&#8596;',
    title: ':left_right_arrow:',
    description: 'LEFT_RIGHT_ARROW',
  },
  {
    type: 7,
    selected: false,
    image: '1f504.png',
    code_decimal: '&#128260;',
    title: ':arrows_counterclockwise:',
    description: 'ARROWS_COUNTERCLOCKWISE',
  },
  {
    type: 7,
    selected: false,
    image: '21aa.png',
    code_decimal: '&#8618;',
    title: ':arrow_right_hook:',
    description: 'ARROW_RIGHT_HOOK',
  },
  {
    type: 7,
    selected: false,
    image: '21a9.png',
    code_decimal: '&#8617;',
    title: ':leftwards_arrow_with_hook:',
    description: 'LEFTWARDS_ARROW_WITH_HOOK',
  },
  {
    type: 7,
    selected: false,
    image: '2934.png',
    code_decimal: '&#10548;',
    title: ':arrow_heading_up:',
    description: 'ARROW_HEADING_UP',
  },
  {
    type: 7,
    selected: false,
    image: '2935.png',
    code_decimal: '&#10549;',
    title: ':arrow_heading_down:',
    description: 'ARROW_HEADING_DOWN',
  },
  {
    type: 7,
    selected: false,
    image: '1f500.png',
    code_decimal: '&#128256;',
    title: ':twisted_rightwards_arrows:',
    description: 'TWISTED_RIGHTWARDS_ARROWS',
  },
  {
    type: 7,
    selected: false,
    image: '1f501.png',
    code_decimal: '&#128257;',
    title: ':repeat:',
    description: 'REPEAT',
  },
  {
    type: 7,
    selected: false,
    image: '1f502.png',
    code_decimal: '&#128258;',
    title: ':repeat_one:',
    description: 'REPEAT_ONE',
  },
  {
    type: 7,
    selected: false,
    image: '0023-20e3.png',
    code_decimal: '&#35;&#65039;&#8419;',
    title: ':hash:',
    description: 'HASH',
  },
  {
    type: 7,
    selected: false,
    image: '0030-20e3.png',
    code_decimal: '&#48;&#65039;&#8419;',
    title: ':zero:',
    description: 'ZERO',
  },
  {
    type: 7,
    selected: false,
    image: '0031-20e3.png',
    code_decimal: '&#49;&#65039;&#8419;',
    title: ':one:',
    description: 'ONE',
  },
  {
    type: 7,
    selected: false,
    image: '0032-20e3.png',
    code_decimal: '&#50;&#65039;&#8419;',
    title: ':two:',
    description: 'TWO',
  },
  {
    type: 7,
    selected: false,
    image: '0033-20e3.png',
    code_decimal: '&#51;&#65039;&#8419;',
    title: ':three:',
    description: 'THREE',
  },
  {
    type: 7,
    selected: false,
    image: '0034-20e3.png',
    code_decimal: '&#52;&#65039;&#8419;',
    title: ':four:',
    description: 'FOUR',
  },
  {
    type: 7,
    selected: false,
    image: '0035-20e3.png',
    code_decimal: '&#53;&#65039;&#8419;',
    title: ':five:',
    description: 'FIVE',
  },
  {
    type: 7,
    selected: false,
    image: '0036-20e3.png',
    code_decimal: '&#54;&#65039;&#8419;',
    title: ':six:',
    description: 'SIX',
  },
  {
    type: 7,
    selected: false,
    image: '0037-20e3.png',
    code_decimal: '&#55;&#65039;&#8419;',
    title: ':seven:',
    description: 'SEVEN',
  },
  {
    type: 7,
    selected: false,
    image: '0038-20e3.png',
    code_decimal: '&#56;&#65039;&#8419;',
    title: ':eight:',
    description: 'EIGHT',
  },
  {
    type: 7,
    selected: false,
    image: '0039-20e3.png',
    code_decimal: '&#57;&#65039;&#8419;',
    title: ':nine:',
    description: 'NINE',
  },
  {
    type: 7,
    selected: false,
    image: '1f51f.png',
    code_decimal: '&#128287;',
    title: ':keycap_ten:',
    description: 'KEYCAP_TEN',
  },
  {
    type: 7,
    selected: false,
    image: '1f522.png',
    code_decimal: '&#128290;',
    title: ':1234:',
    description: '1234',
  },
  {
    type: 7,
    selected: false,
    image: '1f524.png',
    code_decimal: '&#128292;',
    title: ':abc:',
    description: 'ABC',
  },
  {
    type: 7,
    selected: false,
    image: '1f521.png',
    code_decimal: '&#128289;',
    title: ':abcd:',
    description: 'ABCD',
  },
  {
    type: 7,
    selected: false,
    image: '1f520.png',
    code_decimal: '&#128288;',
    title: ':capital_abcd:',
    description: 'CAPITAL_ABCD',
  },
  {
    type: 7,
    selected: false,
    image: '2139.png',
    code_decimal: '&#8505;',
    title: ':information_source:',
    description: 'INFORMATION_SOURCE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4f6.png',
    code_decimal: '&#128246;',
    title: ':signal_strength:',
    description: 'SIGNAL_STRENGTH',
  },
  {
    type: 7,
    selected: false,
    image: '1f3a6.png',
    code_decimal: '&#127910;',
    title: ':cinema:',
    description: 'CINEMA',
  },
  {
    type: 7,
    selected: false,
    image: '1f523.png',
    code_decimal: '&#128291;',
    title: ':symbols:',
    description: 'SYMBOLS',
  },
  {
    type: 7,
    selected: false,
    image: '2795.png',
    code_decimal: '&#10133;',
    title: ':heavy_plus_sign:',
    description: 'HEAVY_PLUS_SIGN',
  },
  {
    type: 7,
    selected: false,
    image: '2796.png',
    code_decimal: '&#10134;',
    title: ':heavy_minus_sign:',
    description: 'HEAVY_MINUS_SIGN',
  },
  {
    type: 7,
    selected: false,
    image: '3030.png',
    code_decimal: '&#12336;',
    title: ':wavy_dash:',
    description: 'WAVY_DASH',
  },
  {
    type: 7,
    selected: false,
    image: '2797.png',
    code_decimal: '&#10135;',
    title: ':heavy_division_sign:',
    description: 'HEAVY_DIVISION_SIGN',
  },
  {
    type: 7,
    selected: false,
    image: '2716.png',
    code_decimal: '&#10006;',
    title: ':heavy_multiplication_x:',
    description: 'HEAVY_MULTIPLICATION_X',
  },
  {
    type: 7,
    selected: false,
    image: '2714.png',
    code_decimal: '&#10004;',
    title: ':heavy_check_mark:',
    description: 'HEAVY_CHECK_MARK',
  },
  {
    type: 7,
    selected: false,
    image: '1f503.png',
    code_decimal: '&#128259;',
    title: ':arrows_clockwise:',
    description: 'ARROWS_CLOCKWISE',
  },
  {
    type: 7,
    selected: false,
    image: '2122.png',
    code_decimal: '&#8482;',
    title: ':tm:',
    description: 'TM',
  },
  {
    type: 7,
    selected: false,
    image: '00a9.png',
    code_decimal: '&#169;',
    title: ':copyright:',
    description: 'COPYRIGHT',
  },
  {
    type: 7,
    selected: false,
    image: '00ae.png',
    code_decimal: '&#174;',
    title: ':registered:',
    description: 'REGISTERED',
  },
  {
    type: 7,
    selected: false,
    image: '1f4b1.png',
    code_decimal: '&#128177;',
    title: ':currency_exchange:',
    description: 'CURRENCY_EXCHANGE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4b2.png',
    code_decimal: '&#128178;',
    title: ':heavy_dollar_sign:',
    description: 'HEAVY_DOLLAR_SIGN',
  },
  {
    type: 7,
    selected: false,
    image: '27b0.png',
    code_decimal: '&#10160;',
    title: ':cHaloContants.PATH_IMAGE_EMOJIy_loop:',
    description: 'CURLY_LOOP',
  },
  {
    type: 7,
    selected: false,
    image: '27bf.png',
    code_decimal: '&#10175;',
    title: ':loop:',
    description: 'LOOP',
  },
  {
    type: 7,
    selected: false,
    image: '303d.png',
    code_decimal: '&#12349;',
    title: ':part_alternation_mark:',
    description: 'PART_ALTERNATION_MARK',
  },
  {
    type: 7,
    selected: false,
    image: '2757.png',
    code_decimal: '&#10071;',
    title: ':exclamation:',
    description: 'EXCLAMATION',
  },
  {
    type: 7,
    selected: false,
    image: '2753.png',
    code_decimal: '&#10067;',
    title: ':question:',
    description: 'QUESTION',
  },
  {
    type: 7,
    selected: false,
    image: '2755.png',
    code_decimal: '&#10069;',
    title: ':grey_exclamation:',
    description: 'GREY_EXCLAMATION',
  },
  {
    type: 7,
    selected: false,
    image: '2754.png',
    code_decimal: '&#10068;',
    title: ':grey_question:',
    description: 'GREY_QUESTION',
  },
  {
    type: 7,
    selected: false,
    image: '203c.png',
    code_decimal: '&#8252;',
    title: ':bangbang:',
    description: 'BANGBANG',
  },
  {
    type: 7,
    selected: false,
    image: '2049.png',
    code_decimal: '&#8265;',
    title: ':interrobang:',
    description: 'INTERROBANG',
  },
  {
    type: 7,
    selected: false,
    image: '274c.png',
    code_decimal: '&#10060;',
    title: ':x:',
    description: 'X',
  },
  {
    type: 7,
    selected: false,
    image: '2b55.png',
    code_decimal: '&#11093;',
    title: ':o:',
    description: 'O',
  },
  {
    type: 7,
    selected: false,
    image: '1f4af.png',
    code_decimal: '&#128175;',
    title: ':100:',
    description: '100',
  },
  {
    type: 7,
    selected: false,
    image: '1f51a.png',
    code_decimal: '&#128282;',
    title: ':end:',
    description: 'END',
  },
  {
    type: 7,
    selected: false,
    image: '1f519.png',
    code_decimal: '&#128281;',
    title: ':back:',
    description: 'BACK',
  },
  {
    type: 7,
    selected: false,
    image: '1f51b.png',
    code_decimal: '&#128283;',
    title: ':on:',
    description: 'ON',
  },
  {
    type: 7,
    selected: false,
    image: '1f51d.png',
    code_decimal: '&#128285;',
    title: ':top:',
    description: 'TOP',
  },
  {
    type: 7,
    selected: false,
    image: '1f51c.png',
    code_decimal: '&#128284;',
    title: ':soon:',
    description: 'SOON',
  },
  {
    type: 7,
    selected: false,
    image: '1f300.png',
    code_decimal: '&#127744;',
    title: ':cyclone:',
    description: 'CYCLONE',
  },
  {
    type: 7,
    selected: false,
    image: '24c2.png',
    code_decimal: '&#9410;',
    title: ':m:',
    description: 'M',
  },
  {
    type: 7,
    selected: false,
    image: '26ce.png',
    code_decimal: '&#9934;',
    title: ':ophiuchus:',
    description: 'OPHIUCHUS',
  },
  {
    type: 7,
    selected: false,
    image: '1f52f.png',
    code_decimal: '&#128303;',
    title: ':six_pointed_star:',
    description: 'SIX_POINTED_STAR',
  },
  {
    type: 7,
    selected: false,
    image: '1f530.png',
    code_decimal: '&#128304;',
    title: ':beginner:',
    description: 'BEGINNER',
  },
  {
    type: 7,
    selected: false,
    image: '1f531.png',
    code_decimal: '&#128305;',
    title: ':trident:',
    description: 'TRIDENT',
  },
  {
    type: 7,
    selected: false,
    image: '26a0.png',
    code_decimal: '&#9888;',
    title: ':warning:',
    description: 'WARNING',
  },
  {
    type: 7,
    selected: false,
    image: '2668.png',
    code_decimal: '&#9832;',
    title: ':hotsprings:',
    description: 'HOTSPRINGS',
  },
  {
    type: 7,
    selected: false,
    image: '1f3f5.png',
    code_decimal: '&#127989;',
    title: ':rosette:',
    description: 'ROSETTE',
  },
  {
    type: 7,
    selected: false,
    image: '267b.png',
    code_decimal: '&#9851;',
    title: ':recycle:',
    description: 'RECYCLE',
  },
  {
    type: 7,
    selected: false,
    image: '1f4a2.png',
    code_decimal: '&#128162;',
    title: ':anger:',
    description: 'ANGER',
  },
  {
    type: 7,
    selected: false,
    image: '1f4a0.png',
    code_decimal: '&#128160;',
    title: ':diamond_shape_with_a_dot_inside:',
    description: 'DIAMOND_SHAPE_WITH_A_DOT_INSIDE',
  },
  {
    type: 7,
    selected: false,
    image: '2660.png',
    code_decimal: '&#9824;',
    title: ':spades:',
    description: 'SPADES',
  },
  {
    type: 7,
    selected: false,
    image: '2663.png',
    code_decimal: '&#9827;',
    title: ':clubs:',
    description: 'CLUBS',
  },
  {
    type: 7,
    selected: false,
    image: '2665.png',
    code_decimal: '&#9829;',
    title: ':hearts:',
    description: 'HEARTS',
  },
  {
    type: 7,
    selected: false,
    image: '2666.png',
    code_decimal: '&#9830;',
    title: ':diamonds:',
    description: 'DIAMONDS',
  },
  {
    type: 7,
    selected: false,
    image: '2611.png',
    code_decimal: '&#9745;',
    title: ':ballot_box_with_check:',
    description: 'BALLOT_BOX_WITH_CHECK',
  },
  {
    type: 7,
    selected: false,
    image: '26aa.png',
    code_decimal: '&#9898;',
    title: ':white_circle:',
    description: 'WHITE_CIRCLE',
  },
  {
    type: 7,
    selected: false,
    image: '26ab.png',
    code_decimal: '&#9899;',
    title: ':black_circle:',
    description: 'BLACK_CIRCLE',
  },
  {
    type: 7,
    selected: false,
    image: '1f518.png',
    code_decimal: '&#128280;',
    title: ':radio_button:',
    description: 'RADIO_BUTTON',
  },
  {
    type: 7,
    selected: false,
    image: '1f534.png',
    code_decimal: '&#128308;',
    title: ':red_circle:',
    description: 'RED_CIRCLE',
  },
  {
    type: 7,
    selected: false,
    image: '1f535.png',
    code_decimal: '&#128309;',
    title: ':large_blue_circle:',
    description: 'LARGE_BLUE_CIRCLE',
  },
  {
    type: 7,
    selected: false,
    image: '1f53a.png',
    code_decimal: '&#128314;',
    title: ':small_red_triangle:',
    description: 'SMALL_RED_TRIANGLE',
  },
  {
    type: 7,
    selected: false,
    image: '1f53b.png',
    code_decimal: '&#128315;',
    title: ':small_red_triangle_down:',
    description: 'SMALL_RED_TRIANGLE_DOWN',
  },
  {
    type: 7,
    selected: false,
    image: '1f538.png',
    code_decimal: '&#128312;',
    title: ':small_orange_diamond:',
    description: 'SMALL_ORANGE_DIAMOND',
  },
  {
    type: 7,
    selected: false,
    image: '1f539.png',
    code_decimal: '&#128313;',
    title: ':small_blue_diamond:',
    description: 'SMALL_BLUE_DIAMOND',
  },
  {
    type: 7,
    selected: false,
    image: '1f536.png',
    code_decimal: '&#128310;',
    title: ':large_orange_diamond:',
    description: 'LARGE_ORANGE_DIAMOND',
  },
  {
    type: 7,
    selected: false,
    image: '1f537.png',
    code_decimal: '&#128311;',
    title: ':large_blue_diamond:',
    description: 'LARGE_BLUE_DIAMOND',
  },
  {
    type: 7,
    selected: false,
    image: '25aa.png',
    code_decimal: '&#9642;',
    title: ':black_small_square:',
    description: 'BLACK_SMALL_SQUARE',
  },
  {
    type: 7,
    selected: false,
    image: '25ab.png',
    code_decimal: '&#9643;',
    title: ':white_small_square:',
    description: 'WHITE_SMALL_SQUARE',
  },
  {
    type: 7,
    selected: false,
    image: '2b1b.png',
    code_decimal: '&#11035;',
    title: ':black_large_square:',
    description: 'BLACK_LARGE_SQUARE',
  },
  {
    type: 7,
    selected: false,
    image: '2b1c.png',
    code_decimal: '&#11036;',
    title: ':white_large_square:',
    description: 'WHITE_LARGE_SQUARE',
  },
  {
    type: 7,
    selected: false,
    image: '25fc.png',
    code_decimal: '&#9724;',
    title: ':black_medium_square:',
    description: 'BLACK_MEDIUM_SQUARE',
  },
  {
    type: 7,
    selected: false,
    image: '25fb.png',
    code_decimal: '&#9723;',
    title: ':white_medium_square:',
    description: 'WHITE_MEDIUM_SQUARE',
  },
  {
    type: 7,
    selected: false,
    image: '25fe.png',
    code_decimal: '&#9726;',
    title: ':black_medium_small_square:',
    description: 'BLACK_MEDIUM_SMALL_SQUARE',
  },
  {
    type: 7,
    selected: false,
    image: '25fd.png',
    code_decimal: '&#9725;',
    title: ':white_medium_small_square:',
    description: 'WHITE_MEDIUM_SMALL_SQUARE',
  },
  {
    type: 7,
    selected: false,
    image: '1f532.png',
    code_decimal: '&#128306;',
    title: ':black_square_button:',
    description: 'BLACK_SQUARE_BUTTON',
  },
  {
    type: 7,
    selected: false,
    image: '1f533.png',
    code_decimal: '&#128307;',
    title: ':white_square_button:',
    description: 'WHITE_SQUARE_BUTTON',
  },
  {
    type: 7,
    selected: false,
    image: '1f550.png',
    code_decimal: '&#128336;',
    title: ':clock1:',
    description: 'CLOCK1',
  },
  {
    type: 7,
    selected: false,
    image: '1f551.png',
    code_decimal: '&#128337;',
    title: ':clock2:',
    description: 'CLOCK2',
  },
  {
    type: 7,
    selected: false,
    image: '1f552.png',
    code_decimal: '&#128338;',
    title: ':clock3:',
    description: 'CLOCK3',
  },
  {
    type: 7,
    selected: false,
    image: '1f553.png',
    code_decimal: '&#128339;',
    title: ':clock4:',
    description: 'CLOCK4',
  },
  {
    type: 7,
    selected: false,
    image: '1f554.png',
    code_decimal: '&#128340;',
    title: ':clock5:',
    description: 'CLOCK5',
  },
  {
    type: 7,
    selected: false,
    image: '1f555.png',
    code_decimal: '&#128341;',
    title: ':clock6:',
    description: 'CLOCK6',
  },
  {
    type: 7,
    selected: false,
    image: '1f556.png',
    code_decimal: '&#128342;',
    title: ':clock7:',
    description: 'CLOCK7',
  },
  {
    type: 7,
    selected: false,
    image: '1f557.png',
    code_decimal: '&#128343;',
    title: ':clock8:',
    description: 'CLOCK8',
  },
  {
    type: 7,
    selected: false,
    image: '1f558.png',
    code_decimal: '&#128344;',
    title: ':clock9:',
    description: 'CLOCK9',
  },
  {
    type: 7,
    selected: false,
    image: '1f559.png',
    code_decimal: '&#128345;',
    title: ':clock10:',
    description: 'CLOCK10',
  },
  {
    type: 7,
    selected: false,
    image: '1f55a.png',
    code_decimal: '&#128346;',
    title: ':clock11:',
    description: 'CLOCK11',
  },
  {
    type: 7,
    selected: false,
    image: '1f55b.png',
    code_decimal: '&#128347;',
    title: ':clock12:',
    description: 'CLOCK12',
  },
  {
    type: 7,
    selected: false,
    image: '1f55c.png',
    code_decimal: '&#128348;',
    title: ':clock130:',
    description: 'CLOCK130',
  },
  {
    type: 7,
    selected: false,
    image: '1f55d.png',
    code_decimal: '&#128349;',
    title: ':clock230:',
    description: 'CLOCK230',
  },
  {
    type: 7,
    selected: false,
    image: '1f55e.png',
    code_decimal: '&#128350;',
    title: ':clock330:',
    description: 'CLOCK330',
  },
  {
    type: 7,
    selected: false,
    image: '1f55f.png',
    code_decimal: '&#128351;',
    title: ':clock430:',
    description: 'CLOCK430',
  },
  {
    type: 7,
    selected: false,
    image: '1f560.png',
    code_decimal: '&#128352;',
    title: ':clock530:',
    description: 'CLOCK530',
  },
  {
    type: 7,
    selected: false,
    image: '1f561.png',
    code_decimal: '&#128353;',
    title: ':clock630:',
    description: 'CLOCK630',
  },
  {
    type: 7,
    selected: false,
    image: '1f562.png',
    code_decimal: '&#128354;',
    title: ':clock730:',
    description: 'CLOCK730',
  },
  {
    type: 7,
    selected: false,
    image: '1f563.png',
    code_decimal: '&#128355;',
    title: ':clock830:',
    description: 'CLOCK830',
  },
  {
    type: 7,
    selected: false,
    image: '1f564.png',
    code_decimal: '&#128356;',
    title: ':clock930:',
    description: 'CLOCK930',
  },
  {
    type: 7,
    selected: false,
    image: '1f565.png',
    code_decimal: '&#128357;',
    title: ':clock1030:',
    description: 'CLOCK1030',
  },
  {
    type: 7,
    selected: false,
    image: '1f566.png',
    code_decimal: '&#128358;',
    title: ':clock1130:',
    description: 'CLOCK1130',
  },
  {
    type: 7,
    selected: false,
    image: '1f567.png',
    code_decimal: '&#128359;',
    title: ':clock1230:',
    description: 'CLOCK1230',
  },
];
export default jsonEmoji7;
