/* eslint-disable camelcase */
const jsonEmoji_1 = [
  {
    type: 1,
    selected: false,
    image: '1f600.png',
    code_decimal: '&#128512;',
    title: ':grinning:',
    description: 'GRINNING',
    code: ':)',
  },
  {
    type: 1,
    selected: false,
    image: '1f601.png',
    code_decimal: '&#128513;',
    title: ':grin:',
    description: 'GRIN',
    code: ':D',
  },
  {
    type: 1,
    selected: false,
    image: '1f602.png',
    code_decimal: '&#128514;',
    title: ':joy:',
    description: 'JOY',
    code: ':(',
  },
  {
    type: 1,
    selected: false,
    image: '1f603.png',
    code_decimal: '&#128515;',
    title: ':smiley:',
    description: 'SMILEY',
  },
  {
    type: 1,
    selected: false,
    image: '1f604.png',
    code_decimal: '&#128516;',
    title: ':smile:',
    description: 'SMILE',
  },
  {
    type: 1,
    selected: false,
    image: '1f605.png',
    code_decimal: '&#128517;',
    title: ':sweat_smile:',
    description: 'SWEAT_SMILE',
  },
  {
    type: 1,
    selected: false,
    image: '1f606.png',
    code_decimal: '&#128518;',
    title: ':laughing:',
    description: 'LAUGHING',
  },
  {
    type: 1,
    selected: false,
    image: '1f607.png',
    code_decimal: '&#128519;',
    title: ':innocent:',
    description: 'INNOCENT',
  },
  {
    type: 1,
    selected: false,
    image: '1f608.png',
    code_decimal: '&#128520;',
    title: ':smiling_imp:',
    description: 'SMILING_IMP',
  },
  {
    type: 1,
    selected: false,
    image: '1f47f.png',
    code_decimal: '&#128127;',
    title: ':imp:',
    description: 'IMP',
  },
  {
    type: 1,
    selected: false,
    image: '1f609.png',
    code_decimal: '&#128521;',
    title: ':wink:',
    description: 'WINK',
  },
  {
    type: 1,
    selected: false,
    image: '1f60a.png',
    code_decimal: '&#128522;',
    title: ':blush:',
    description: 'BLUSH',
  },
  {
    type: 1,
    selected: false,
    image: '263a.png',
    code_decimal: '&#9786;',
    title: ':relaxed:',
    description: 'RELAXED',
  },
  {
    type: 1,
    selected: false,
    image: '1f60b.png',
    code_decimal: '&#128523;',
    title: ':yum:',
    description: 'YUM',
  },
  {
    type: 1,
    selected: false,
    image: '1f60c.png',
    code_decimal: '&#128524;',
    title: ':relieved:',
    description: 'RELIEVED',
  },
  {
    type: 1,
    selected: false,
    image: '1f60d.png',
    code_decimal: '&#128525;',
    title: ':heart_eyes:',
    description: 'HEART_EYES',
  },
  {
    type: 1,
    selected: false,
    image: '1f60e.png',
    code_decimal: '&#128526;',
    title: ':sunglasses:',
    description: 'SUNGLASSES',
  },
  {
    type: 1,
    selected: false,
    image: '1f60f.png',
    code_decimal: '&#128527;',
    title: ':smirk:',
    description: 'SMIRK',
  },
  {
    type: 1,
    selected: false,
    image: '1f610.png',
    code_decimal: '&#128528;',
    title: ':neutral_face:',
    description: 'NEUTRAL_FACE',
  },
  {
    type: 1,
    selected: false,
    image: '1f611.png',
    code_decimal: '&#128529;',
    title: ':expressionless:',
    description: 'EXPRESSIONLESS',
  },
  {
    type: 1,
    selected: false,
    image: '1f612.png',
    code_decimal: '&#128530;',
    title: ':unamused:',
    description: 'UNAMUSED',
  },
  {
    type: 1,
    selected: false,
    image: '1f613.png',
    code_decimal: '&#128531;',
    title: ':sweat:',
    description: 'SWEAT',
  },
  {
    type: 1,
    selected: false,
    image: '1f614.png',
    code_decimal: '&#128532;',
    title: ':pensive:',
    description: 'PENSIVE',
  },
  {
    type: 1,
    selected: false,
    image: '1f615.png',
    code_decimal: '&#128533;',
    title: ':confused:',
    description: 'CONFUSED',
  },
  {
    type: 1,
    selected: false,
    image: '1f616.png',
    code_decimal: '&#128534;',
    title: ':confounded:',
    description: 'CONFOUNDED',
  },
  {
    type: 1,
    selected: false,
    image: '1f617.png',
    code_decimal: '&#128535;',
    title: ':kissing:',
    description: 'KISSING',
  },
  {
    type: 1,
    selected: false,
    image: '1f618.png',
    code_decimal: '&#128536;',
    title: ':kissing_heart:',
    description: 'KISSING_HEART',
  },
  {
    type: 1,
    selected: false,
    image: '1f619.png',
    code_decimal: '&#128537;',
    title: ':kissing_smiling_eyes:',
    description: 'KISSING_SMILING_EYES',
  },
  {
    type: 1,
    selected: false,
    image: '1f61a.png',
    code_decimal: '&#128538;',
    title: ':kissing_closed_eyes:',
    description: 'KISSING_CLOSED_EYES',
  },
  {
    type: 1,
    selected: false,
    image: '1f61b.png',
    code_decimal: '&#128539;',
    title: ':stuck_out_tongue:',
    description: 'STUCK_OUT_TONGUE',
  },
  {
    type: 1,
    selected: false,
    image: '1f61c.png',
    code_decimal: '&#128540;',
    title: ':stuck_out_tongue_winking_eye:',
    description: 'STUCK_OUT_TONGUE_WINKING_EYE',
  },
  {
    type: 1,
    selected: false,
    image: '1f61d.png',
    code_decimal: '&#128541;',
    title: ':stuck_out_tongue_closed_eyes:',
    description: 'STUCK_OUT_TONGUE_CLOSED_EYES',
  },
  {
    type: 1,
    selected: false,
    image: '1f61e.png',
    code_decimal: '&#128542;',
    title: ':disappointed:',
    description: 'DISAPPOINTED',
  },
  {
    type: 1,
    selected: false,
    image: '1f61f.png',
    code_decimal: '&#128543;',
    title: ':worried:',
    description: 'WORRIED',
  },
  {
    type: 1,
    selected: false,
    image: '1f620.png',
    code_decimal: '&#128544;',
    title: ':angry:',
    description: 'ANGRY',
  },
  {
    type: 1,
    selected: false,
    image: '1f621.png',
    code_decimal: '&#128545;',
    title: ':rage:',
    description: 'RAGE',
  },
  {
    type: 1,
    selected: false,
    image: '1f622.png',
    code_decimal: '&#128546;',
    title: ':cry:',
    description: 'CRY',
  },
  {
    type: 1,
    selected: false,
    image: '1f623.png',
    code_decimal: '&#128547;',
    title: ':persevere:',
    description: 'PERSEVERE',
  },
  {
    type: 1,
    selected: false,
    image: '1f624.png',
    code_decimal: '&#128548;',
    title: ':triumph:',
    description: 'TRIUMPH',
  },
  {
    type: 1,
    selected: false,
    image: '1f625.png',
    code_decimal: '&#128549;',
    title: ':disappointed_relieved:',
    description: 'DISAPPOINTED_RELIEVED',
  },
  {
    type: 1,
    selected: false,
    image: '1f626.png',
    code_decimal: '&#128550;',
    title: ':frowning:',
    description: 'FROWNING',
  },
  {
    type: 1,
    selected: false,
    image: '1f627.png',
    code_decimal: '&#128551;',
    title: ':anguished:',
    description: 'ANGUISHED',
  },
  {
    type: 1,
    selected: false,
    image: '1f628.png',
    code_decimal: '&#128552;',
    title: ':fearful:',
    description: 'FEARFUL',
  },
  {
    type: 1,
    selected: false,
    image: '1f629.png',
    code_decimal: '&#128553;',
    title: ':weary:',
    description: 'WEARY',
  },
  {
    type: 1,
    selected: false,
    image: '1f62a.png',
    code_decimal: '&#128554;',
    title: ':sleepy:',
    description: 'SLEEPY',
  },
  {
    type: 1,
    selected: false,
    image: '1f62b.png',
    code_decimal: '&#128555;',
    title: ':tired_face:',
    description: 'TIRED_FACE',
  },
  {
    type: 1,
    selected: false,
    image: '1f62c.png',
    code_decimal: '&#128556;',
    title: ':grimacing:',
    description: 'GRIMACING',
  },
  {
    type: 1,
    selected: false,
    image: '1f62d.png',
    code_decimal: '&#128557;',
    title: ':sob:',
    description: 'SOB',
  },
  {
    type: 1,
    selected: false,
    image: '1f62e.png',
    code_decimal: '&#128558;',
    title: ':open_mouth:',
    description: 'OPEN_MOUTH',
  },
  {
    type: 1,
    selected: false,
    image: '1f62f.png',
    code_decimal: '&#128559;',
    title: ':hushed:',
    description: 'HUSHED',
  },
  {
    type: 1,
    selected: false,
    image: '1f630.png',
    code_decimal: '&#128560;',
    title: ':cold_sweat:',
    description: 'COLD_SWEAT',
  },
  {
    type: 1,
    selected: false,
    image: '1f631.png',
    code_decimal: '&#128561;',
    title: ':scream:',
    description: 'SCREAM',
  },
  {
    type: 1,
    selected: false,
    image: '1f632.png',
    code_decimal: '&#128562;',
    title: ':astonished:',
    description: 'ASTONISHED',
  },
  {
    type: 1,
    selected: false,
    image: '1f633.png',
    code_decimal: '&#128563;',
    title: ':flushed:',
    description: 'FLUSHED',
  },
  {
    type: 1,
    selected: false,
    image: '1f634.png',
    code_decimal: '&#128564;',
    title: ':sleeping:',
    description: 'SLEEPING',
  },
  {
    type: 1,
    selected: false,
    image: '1f635.png',
    code_decimal: '&#128565;',
    title: ':dizzy_face:',
    description: 'DIZZY_FACE',
  },
  {
    type: 1,
    selected: false,
    image: '1f636.png',
    code_decimal: '&#128566;',
    title: ':no_mouth:',
    description: 'NO_MOUTH',
  },
  {
    type: 1,
    selected: false,
    image: '1f637.png',
    code_decimal: '&#128567;',
    title: ':mask:',
    description: 'MASK',
  },
  {
    type: 1,
    selected: false,
    image: '1f641.png',
    code_decimal: '&#128577;',
    title: ':slight_frown:',
    description: 'SLIGHT_FROWN',
  },
  {
    type: 1,
    selected: false,
    image: '1f642.png',
    code_decimal: '&#128578;',
    title: ':slight_smile:',
    description: 'SLIGHT_SMILE',
  },
  {
    type: 1,
    selected: false,
    image: '1f638.png',
    code_decimal: '&#128568;',
    title: ':smile_cat:',
    description: 'SMILE_CAT',
  },
  {
    type: 1,
    selected: false,
    image: '1f639.png',
    code_decimal: '&#128569;',
    title: ':joy_cat:',
    description: 'JOY_CAT',
  },
  {
    type: 1,
    selected: false,
    image: '1f63a.png',
    code_decimal: '&#128570;',
    title: ':smiley_cat:',
    description: 'SMILEY_CAT',
  },
  {
    type: 1,
    selected: false,
    image: '1f63b.png',
    code_decimal: '&#128571;',
    title: ':heart_eyes_cat:',
    description: 'HEART_EYES_CAT',
  },
  {
    type: 1,
    selected: false,
    image: '1f63c.png',
    code_decimal: '&#128572;',
    title: ':smirk_cat:',
    description: 'SMIRK_CAT',
  },
  {
    type: 1,
    selected: false,
    image: '1f63d.png',
    code_decimal: '&#128573;',
    title: ':kissing_cat:',
    description: 'KISSING_CAT',
  },
  {
    type: 1,
    selected: false,
    image: '1f63e.png',
    code_decimal: '&#128574;',
    title: ':pouting_cat:',
    description: 'POUTING_CAT',
  },
  {
    type: 1,
    selected: false,
    image: '1f63f.png',
    code_decimal: '&#128575;',
    title: ':crying_cat_face:',
    description: 'CRYING_CAT_FACE',
  },
  {
    type: 1,
    selected: false,
    image: '1f640.png',
    code_decimal: '&#128576;',
    title: ':scream_cat:',
    description: 'SCREAM_CAT',
  },
  {
    type: 1,
    selected: false,
    image: '1f463.png',
    code_decimal: '&#128099;',
    title: ':footprints:',
    description: 'FOOTPRINTS',
  },
  {
    type: 1,
    selected: false,
    image: '1f464.png',
    code_decimal: '&#128100;',
    title: ':bust_in_silhouette:',
    description: 'BUST_IN_SILHOUETTE',
  },
  {
    type: 1,
    selected: false,
    image: '1f465.png',
    code_decimal: '&#128101;',
    title: ':busts_in_silhouette:',
    description: 'BUSTS_IN_SILHOUETTE',
  },
  {
    type: 1,
    selected: false,
    image: '1f574.png',
    code_decimal: '&#128372;',
    title: ':levitate:',
    description: 'LEVITATE',
  },
  {
    type: 1,
    selected: false,
    image: '1f575.png',
    code_decimal: '&#128373;',
    title: ':spy:',
    description: 'SPY',
  },
  {
    type: 1,
    selected: false,
    image: '1f476.png',
    code_decimal: '&#128118;',
    title: ':baby:',
    description: 'BABY',
  },
  {
    type: 1,
    selected: false,
    image: '1f466.png',
    code_decimal: '&#128102;',
    title: ':boy:',
    description: 'BOY',
  },
  {
    type: 1,
    selected: false,
    image: '1f467.png',
    code_decimal: '&#128103;',
    title: ':girl:',
    description: 'GIRL',
  },
  {
    type: 1,
    selected: false,
    image: '1f468.png',
    code_decimal: '&#128104;',
    title: ':man:',
    description: 'MAN',
  },
  {
    type: 1,
    selected: false,
    image: '1f469.png',
    code_decimal: '&#128105;',
    title: ':woman:',
    description: 'WOMAN',
  },
  {
    type: 1,
    selected: false,
    image: '1f46a.png',
    code_decimal: '&#128106;',
    title: ':family:',
    description: 'FAMILY',
  },
  {
    type: 1,
    selected: false,
    image: '1f468-1f469-1f467.png',
    code_decimal: '&#128104;&#8205;&#128105;&#8205;&#128103;',
    title: ':family_mwg:',
    description: 'FAMILY_MWG',
  },
  {
    type: 1,
    selected: false,
    image: '1f468-1f469-1f467-1f466.png',
    code_decimal: '&#128104;&#8205;&#128105;&#8205;&#128103;&#8205;&#128102;',
    title: ':family_mwgb:',
    description: 'FAMILY_MWGB',
  },
  {
    type: 1,
    selected: false,
    image: '1f468-1f469-1f466-1f466.png',
    code_decimal: '&#128104;&#8205;&#128105;&#8205;&#128102;&#8205;&#128102;',
    title: ':family_mwbb:',
    description: 'FAMILY_MWBB',
  },
  {
    type: 1,
    selected: false,
    image: '1f468-1f469-1f467-1f467.png',
    code_decimal: '&#128104;&#8205;&#128105;&#8205;&#128103;&#8205;&#128103;',
    title: ':family_mwgg:',
    description: 'FAMILY_MWGG',
  },
  {
    type: 1,
    selected: false,
    image: '1f469-1f469-1f466.png',
    code_decimal: '&#128105;&#8205;&#128105;&#8205;&#128102;',
    title: ':family_wwb:',
    description: 'FAMILY_WWB',
  },
  {
    type: 1,
    selected: false,
    image: '1f469-1f469-1f467.png',
    code_decimal: '&#128105;&#8205;&#128105;&#8205;&#128103;',
    title: ':family_wwg:',
    description: 'FAMILY_WWG',
  },
  {
    type: 1,
    selected: false,
    image: '1f469-1f469-1f467-1f466.png',
    code_decimal: '&#128105;&#8205;&#128105;&#8205;&#128103;&#8205;&#128102;',
    title: ':family_wwgb:',
    description: 'FAMILY_WWGB',
  },
  {
    type: 1,
    selected: false,
    image: '1f469-1f469-1f466-1f466.png',
    code_decimal: '&#128105;&#8205;&#128105;&#8205;&#128102;&#8205;&#128102;',
    title: ':family_wwbb:',
    description: 'FAMILY_WWBB',
  },
  {
    type: 1,
    selected: false,
    image: '1f469-1f469-1f467-1f467.png',
    code_decimal: '&#128105;&#8205;&#128105;&#8205;&#128103;&#8205;&#128103;',
    title: ':family_wwgg:',
    description: 'FAMILY_WWGG',
  },
  {
    type: 1,
    selected: false,
    image: '1f468-1f468-1f466.png',
    code_decimal: '&#128104;&#8205;&#128104;&#8205;&#128102;',
    title: ':family_mmb:',
    description: 'FAMILY_MMB',
  },
  {
    type: 1,
    selected: false,
    image: '1f468-1f468-1f467.png',
    code_decimal: '&#128104;&#8205;&#128104;&#8205;&#128103;',
    title: ':family_mmg:',
    description: 'FAMILY_MMG',
  },
  {
    type: 1,
    selected: false,
    image: '1f468-1f468-1f467-1f466.png',
    code_decimal: '&#128104;&#8205;&#128104;&#8205;&#128103;&#8205;&#128102;',
    title: ':family_mmgb:',
    description: 'FAMILY_MMGB',
  },
  {
    type: 1,
    selected: false,
    image: '1f468-1f468-1f466-1f466.png',
    code_decimal: '&#128104;&#8205;&#128104;&#8205;&#128102;&#8205;&#128102;',
    title: ':family_mmbb:',
    description: 'FAMILY_MMBB',
  },
  {
    type: 1,
    selected: false,
    image: '1f468-1f468-1f467-1f467.png',
    code_decimal: '&#128104;&#8205;&#128104;&#8205;&#128103;&#8205;&#128103;',
    title: ':family_mmgg:',
    description: 'FAMILY_MMGG',
  },
  {
    type: 1,
    selected: false,
    image: '1f46b.png',
    code_decimal: '&#128107;',
    title: ':couple:',
    description: 'COUPLE',
  },
  {
    type: 1,
    selected: false,
    image: '1f46c.png',
    code_decimal: '&#128108;',
    title: ':two_men_holding_hands:',
    description: 'TWO_MEN_HOLDING_HANDS',
  },
  {
    type: 1,
    selected: false,
    image: '1f46d.png',
    code_decimal: '&#128109;',
    title: ':two_women_holding_hands:',
    description: 'TWO_WOMEN_HOLDING_HANDS',
  },
  {
    type: 1,
    selected: false,
    image: '1f46f.png',
    code_decimal: '&#128111;',
    title: ':dancers:',
    description: 'DANCERS',
  },
  {
    type: 1,
    selected: false,
    image: '1f470.png',
    code_decimal: '&#128112;',
    title: ':bride_with_veil:',
    description: 'BRIDE_WITH_VEIL',
  },
  {
    type: 1,
    selected: false,
    image: '1f471.png',
    code_decimal: '&#128113;',
    title: ':person_with_blond_hair:',
    description: 'PERSON_WITH_BLOND_HAIR',
  },
  {
    type: 1,
    selected: false,
    image: '1f472.png',
    code_decimal: '&#128114;',
    title: ':man_with_gua_pi_mao:',
    description: 'MAN_WITH_GUA_PI_MAO',
  },
  {
    type: 1,
    selected: false,
    image: '1f473.png',
    code_decimal: '&#128115;',
    title: ':man_with_turban:',
    description: 'MAN_WITH_TURBAN',
  },
  {
    type: 1,
    selected: false,
    image: '1f474.png',
    code_decimal: '&#128116;',
    title: ':older_man:',
    description: 'OLDER_MAN',
  },
  {
    type: 1,
    selected: false,
    image: '1f475.png',
    code_decimal: '&#128117;',
    title: ':older_woman:',
    description: 'OLDER_WOMAN',
  },
  {
    type: 1,
    selected: false,
    image: '1f46e.png',
    code_decimal: '&#128110;',
    title: ':cop:',
    description: 'COP',
  },
  {
    type: 1,
    selected: false,
    image: '1f477.png',
    code_decimal: '&#128119;',
    title: ':construction_worker:',
    description: 'CONSTRUCTION_WORKER',
  },
  {
    type: 1,
    selected: false,
    image: '1f478.png',
    code_decimal: '&#128120;',
    title: ':princess:',
    description: 'PRINCESS',
  },
  {
    type: 1,
    selected: false,
    image: '1f482.png',
    code_decimal: '&#128130;',
    title: ':guardsman:',
    description: 'GUARDSMAN',
  },
  {
    type: 1,
    selected: false,
    image: '1f47c.png',
    code_decimal: '&#128124;',
    title: ':angel:',
    description: 'ANGEL',
  },
  {
    type: 1,
    selected: false,
    image: '1f385.png',
    code_decimal: '&#127877;',
    title: ':santa:',
    description: 'SANTA',
  },
  {
    type: 1,
    selected: false,
    image: '1f47b.png',
    code_decimal: '&#128123;',
    title: ':ghost:',
    description: 'GHOST',
  },
  {
    type: 1,
    selected: false,
    image: '1f479.png',
    code_decimal: '&#128121;',
    title: ':japanese_ogre:',
    description: 'JAPANESE_OGRE',
  },
  {
    type: 1,
    selected: false,
    image: '1f47a.png',
    code_decimal: '&#128122;',
    title: ':japanese_goblin:',
    description: 'JAPANESE_GOBLIN',
  },
  {
    type: 1,
    selected: false,
    image: '1f4a9.png',
    code_decimal: '&#128169;',
    title: ':poop:',
    description: 'POOP',
  },
  {
    type: 1,
    selected: false,
    image: '1f480.png',
    code_decimal: '&#128128;',
    title: ':skull:',
    description: 'SKULL',
  },
  {
    type: 1,
    selected: false,
    image: '1f47d.png',
    code_decimal: '&#128125;',
    title: ':alien:',
    description: 'ALIEN',
  },
  {
    type: 1,
    selected: false,
    image: '1f47e.png',
    code_decimal: '&#128126;',
    title: ':space_invader:',
    description: 'SPACE_INVADER',
  },
  {
    type: 1,
    selected: false,
    image: '1f647.png',
    code_decimal: '&#128583;',
    title: ':bow:',
    description: 'BOW',
  },
  {
    type: 1,
    selected: false,
    image: '1f481.png',
    code_decimal: '&#128129;',
    title: ':information_desk_person:',
    description: 'INFORMATION_DESK_PERSON',
  },
  {
    type: 1,
    selected: false,
    image: '1f645.png',
    code_decimal: '&#128581;',
    title: ':no_good:',
    description: 'NO_GOOD',
  },
  {
    type: 1,
    selected: false,
    image: '1f646.png',
    code_decimal: '&#128582;',
    title: ':ok_woman:',
    description: 'OK_WOMAN',
  },
  {
    type: 1,
    selected: false,
    image: '1f64b.png',
    code_decimal: '&#128587;',
    title: ':raising_hand:',
    description: 'RAISING_HAND',
  },
  {
    type: 1,
    selected: false,
    image: '1f64e.png',
    code_decimal: '&#128590;',
    title: ':person_with_pouting_face:',
    description: 'PERSON_WITH_POUTING_FACE',
  },
  {
    type: 1,
    selected: false,
    image: '1f64d.png',
    code_decimal: '&#128589;',
    title: ':person_frowning:',
    description: 'PERSON_FROWNING',
  },
  {
    type: 1,
    selected: false,
    image: '1f486.png',
    code_decimal: '&#128134;',
    title: ':massage:',
    description: 'MASSAGE',
  },
  {
    type: 1,
    selected: false,
    image: '1f487.png',
    code_decimal: '&#128135;',
    title: ':haircut:',
    description: 'HAIRCUT',
  },
  {
    type: 1,
    selected: false,
    image: '1f491.png',
    code_decimal: '&#128145;',
    title: ':couple_with_heart:',
    description: 'COUPLE_WITH_HEART',
  },
  {
    type: 1,
    selected: false,
    image: '1f469-2764-1f469.png',
    code_decimal: '&#128105;&#8205;&#10084;&#65039;&#8205;&#128105;',
    title: ':couple_ww:',
    description: 'COUPLE_WW',
  },
  {
    type: 1,
    selected: false,
    image: '1f468-2764-1f468.png',
    code_decimal: '&#128104;&#8205;&#10084;&#65039;&#8205;&#128104;',
    title: ':couple_mm:',
    description: 'COUPLE_MM',
  },
  {
    type: 1,
    selected: false,
    image: '1f48f.png',
    code_decimal: '&#128143;',
    title: ':couplekiss:',
    description: 'COUPLEKISS',
  },
  {
    type: 1,
    selected: false,
    image: '1f469-2764-1f48b-1f469.png',
    code_decimal:
      '&#128105;&#8205;&#10084;&#65039;&#8205;&#128139;&#8205;&#128105;',
    title: ':kiss_ww:',
    description: 'KISS_WW',
  },
  {
    type: 1,
    selected: false,
    image: '1f468-2764-1f48b-1f468.png',
    code_decimal:
      '&#128104;&#8205;&#10084;&#65039;&#8205;&#128139;&#8205;&#128104;',
    title: ':kiss_mm:',
    description: 'KISS_MM',
  },
  {
    type: 1,
    selected: false,
    image: '1f64c.png',
    code_decimal: '&#128588;',
    title: ':raised_hands:',
    description: 'RAISED_HANDS',
  },
  {
    type: 1,
    selected: false,
    image: '1f44f.png',
    code_decimal: '&#128079;',
    title: ':clap:',
    description: 'CLAP',
  },
  {
    type: 1,
    selected: false,
    image: '1f442.png',
    code_decimal: '&#128066;',
    title: ':ear:',
    description: 'EAR',
  },
  {
    type: 1,
    selected: false,
    image: '1f441.png',
    code_decimal: '&#128065;',
    title: ':eye:',
    description: 'EYE',
  },
  {
    type: 1,
    selected: false,
    image: '1f440.png',
    code_decimal: '&#128064;',
    title: ':eyes:',
    description: 'EYES',
  },
  {
    type: 1,
    selected: false,
    image: '1f443.png',
    code_decimal: '&#128067;',
    title: ':nose:',
    description: 'NOSE',
  },
  {
    type: 1,
    selected: false,
    image: '1f444.png',
    code_decimal: '&#128068;',
    title: ':lips:',
    description: 'LIPS',
  },
  {
    type: 1,
    selected: false,
    image: '1f48b.png',
    code_decimal: '&#128139;',
    title: ':kiss:',
    description: 'KISS',
  },
  {
    type: 1,
    selected: false,
    image: '1f445.png',
    code_decimal: '&#128069;',
    title: ':tongue:',
    description: 'TONGUE',
  },
  {
    type: 1,
    selected: false,
    image: '1f485.png',
    code_decimal: '&#128133;',
    title: ':nail_care:',
    description: 'NAIL_CARE',
  },
  {
    type: 1,
    selected: false,
    image: '1f44b.png',
    code_decimal: '&#128075;',
    title: ':wave:',
    description: 'WAVE',
  },
  {
    type: 1,
    selected: false,
    image: '1f44d.png',
    code_decimal: '&#128077;',
    title: ':thumbsup:',
    description: 'THUMBSUP',
  },
  {
    type: 1,
    selected: false,
    image: '1f44e.png',
    code_decimal: '&#128078;',
    title: ':thumbsdown:',
    description: 'THUMBSDOWN',
  },
  {
    type: 1,
    selected: false,
    image: '261d.png',
    code_decimal: '&#9757;',
    title: ':point_up:',
    description: 'POINT_UP',
  },
  {
    type: 1,
    selected: false,
    image: '1f446.png',
    code_decimal: '&#128070;',
    title: ':point_up_2:',
    description: 'POINT_UP_2',
  },
  {
    type: 1,
    selected: false,
    image: '1f447.png',
    code_decimal: '&#128071;',
    title: ':point_down:',
    description: 'POINT_DOWN',
  },
  {
    type: 1,
    selected: false,
    image: '1f448.png',
    code_decimal: '&#128072;',
    title: ':point_left:',
    description: 'POINT_LEFT',
  },
  {
    type: 1,
    selected: false,
    image: '1f449.png',
    code_decimal: '&#128073;',
    title: ':point_right:',
    description: 'POINT_RIGHT',
  },
  {
    type: 1,
    selected: false,
    image: '1f44c.png',
    code_decimal: '&#128076;',
    title: ':ok_hand:',
    description: 'OK_HAND',
  },
  {
    type: 1,
    selected: false,
    image: '270c.png',
    code_decimal: '&#9996;',
    title: ':v:',
    description: 'V',
  },
  {
    type: 1,
    selected: false,
    image: '1f44a.png',
    code_decimal: '&#128074;',
    title: ':punch:',
    description: 'PUNCH',
  },
  {
    type: 1,
    selected: false,
    image: '270a.png',
    code_decimal: '&#9994;',
    title: ':fist:',
    description: 'FIST',
  },
  {
    type: 1,
    selected: false,
    image: '270b.png',
    code_decimal: '&#9995;',
    title: ':raised_hand:',
    description: 'RAISED_HAND',
  },
  {
    type: 1,
    selected: false,
    image: '1f4aa.png',
    code_decimal: '&#128170;',
    title: ':muscle:',
    description: 'MUSCLE',
  },
  {
    type: 1,
    selected: false,
    image: '1f450.png',
    code_decimal: '&#128080;',
    title: ':open_hands:',
    description: 'OPEN_HANDS',
  },
  {
    type: 1,
    selected: false,
    image: '1f58e.png',
    code_decimal: '&#9997;',
    title: ':writing_hand:',
    description: 'WRITING_HAND',
  },
  {
    type: 1,
    selected: false,
    image: '1f590.png',
    code_decimal: '&#128400;',
    title: ':hand_splayed:',
    description: 'HAND_SPLAYED',
  },
  {
    type: 1,
    selected: false,
    image: '1f595.png',
    code_decimal: '&#128405;',
    title: ':middle_finger:',
    description: 'MIDDLE_FINGER',
  },
  {
    type: 1,
    selected: false,
    image: '1f596.png',
    code_decimal: '&#128406;',
    title: ':vulcan:',
    description: 'VULCAN',
  },
  {
    type: 1,
    selected: false,
    image: '1f64f.png',
    code_decimal: '&#128591;',
    title: ':pray:',
    description: 'PRAY',
  },
];

export default jsonEmoji_1;
