const jsonEmoji3 = [
  {
    type: 3,
    selected: false,
    image: '1f346.png',
    code_decimal: '&#127814;',
    title: ':eggplant:',
    description: 'EGGPLANT',
  },
  {
    type: 3,
    selected: false,
    image: '1f33d.png',
    code_decimal: '&#127805;',
    title: ':corn:',
    description: 'CORN',
  },
  {
    type: 3,
    selected: false,
    image: '1f360.png',
    code_decimal: '&#127840;',
    title: ':sweet_potato:',
    description: 'SWEET_POTATO',
  },
  {
    type: 3,
    selected: false,
    image: '1f336.png',
    code_decimal: '&#127798;',
    title: ':hot_pepper:',
    description: 'HOT_PEPPER',
  },
  {
    type: 3,
    selected: false,
    image: '1f347.png',
    code_decimal: '&#127815;',
    title: ':grapes:',
    description: 'GRAPES',
  },
  {
    type: 3,
    selected: false,
    image: '1f348.png',
    code_decimal: '&#127816;',
    title: ':melon:',
    description: 'MELON',
  },
  {
    type: 3,
    selected: false,
    image: '1f349.png',
    code_decimal: '&#127817;',
    title: ':watermelon:',
    description: 'WATERMELON',
  },
  {
    type: 3,
    selected: false,
    image: '1f34a.png',
    code_decimal: '&#127818;',
    title: ':tangerine:',
    description: 'TANGERINE',
  },
  {
    type: 3,
    selected: false,
    image: '1f34b.png',
    code_decimal: '&#127819;',
    title: ':lemon:',
    description: 'LEMON',
  },
  {
    type: 3,
    selected: false,
    image: '1f34c.png',
    code_decimal: '&#127820;',
    title: ':banana:',
    description: 'BANANA',
  },
  {
    type: 3,
    selected: false,
    image: '1f34d.png',
    code_decimal: '&#127821;',
    title: ':pineapple:',
    description: 'PINEAPPLE',
  },
  {
    type: 3,
    selected: false,
    image: '1f34e.png',
    code_decimal: '&#127822;',
    title: ':apple:',
    description: 'APPLE',
  },
  {
    type: 3,
    selected: false,
    image: '1f34f.png',
    code_decimal: '&#127823;',
    title: ':green_apple:',
    description: 'GREEN_APPLE',
  },
  {
    type: 3,
    selected: false,
    image: '1f350.png',
    code_decimal: '&#127824;',
    title: ':pear:',
    description: 'PEAR',
  },
  {
    type: 3,
    selected: false,
    image: '1f351.png',
    code_decimal: '&#127825;',
    title: ':peach:',
    description: 'PEACH',
  },
  {
    type: 3,
    selected: false,
    image: '1f352.png',
    code_decimal: '&#127826;',
    title: ':cherries:',
    description: 'CHERRIES',
  },
  {
    type: 3,
    selected: false,
    image: '1f353.png',
    code_decimal: '&#127827;',
    title: ':strawberry:',
    description: 'STRAWBERRY',
  },
  {
    type: 3,
    selected: false,
    image: '1f354.png',
    code_decimal: '&#127828;',
    title: ':hamburger:',
    description: 'HAMBURGER',
  },
  {
    type: 3,
    selected: false,
    image: '1f355.png',
    code_decimal: '&#127829;',
    title: ':pizza:',
    description: 'PIZZA',
  },
  {
    type: 3,
    selected: false,
    image: '1f356.png',
    code_decimal: '&#127830;',
    title: ':meat_on_bone:',
    description: 'MEAT_ON_BONE',
  },
  {
    type: 3,
    selected: false,
    image: '1f357.png',
    code_decimal: '&#127831;',
    title: ':poultry_leg:',
    description: 'POULTRY_LEG',
  },
  {
    type: 3,
    selected: false,
    image: '1f358.png',
    code_decimal: '&#127832;',
    title: ':rice_cracker:',
    description: 'RICE_CRACKER',
  },
  {
    type: 3,
    selected: false,
    image: '1f359.png',
    code_decimal: '&#127833;',
    title: ':rice_ball:',
    description: 'RICE_BALL',
  },
  {
    type: 3,
    selected: false,
    image: '1f35a.png',
    code_decimal: '&#127834;',
    title: ':rice:',
    description: 'RICE',
  },
  {
    type: 3,
    selected: false,
    image: '1f35b.png',
    code_decimal: '&#127835;',
    title: ':curry:',
    description: 'CURRY',
  },
  {
    type: 3,
    selected: false,
    image: '1f35c.png',
    code_decimal: '&#127836;',
    title: ':ramen:',
    description: 'RAMEN',
  },
  {
    type: 3,
    selected: false,
    image: '1f35d.png',
    code_decimal: '&#127837;',
    title: ':spaghetti:',
    description: 'SPAGHETTI',
  },
  {
    type: 3,
    selected: false,
    image: '1f35e.png',
    code_decimal: '&#127838;',
    title: ':bread:',
    description: 'BREAD',
  },
  {
    type: 3,
    selected: false,
    image: '1f35f.png',
    code_decimal: '&#127839;',
    title: ':fries:',
    description: 'FRIES',
  },
  {
    type: 3,
    selected: false,
    image: '1f361.png',
    code_decimal: '&#127841;',
    title: ':dango:',
    description: 'DANGO',
  },
  {
    type: 3,
    selected: false,
    image: '1f362.png',
    code_decimal: '&#127842;',
    title: ':oden:',
    description: 'ODEN',
  },
  {
    type: 3,
    selected: false,
    image: '1f363.png',
    code_decimal: '&#127843;',
    title: ':sushi:',
    description: 'SUSHI',
  },
  {
    type: 3,
    selected: false,
    image: '1f364.png',
    code_decimal: '&#127844;',
    title: ':fried_shrimp:',
    description: 'FRIED_SHRIMP',
  },
  {
    type: 3,
    selected: false,
    image: '1f365.png',
    code_decimal: '&#127845;',
    title: ':fish_cake:',
    description: 'FISH_CAKE',
  },
  {
    type: 3,
    selected: false,
    image: '1f366.png',
    code_decimal: '&#127846;',
    title: ':icecream:',
    description: 'ICECREAM',
  },
  {
    type: 3,
    selected: false,
    image: '1f367.png',
    code_decimal: '&#127847;',
    title: ':shaved_ice:',
    description: 'SHAVED_ICE',
  },
  {
    type: 3,
    selected: false,
    image: '1f368.png',
    code_decimal: '&#127848;',
    title: ':ice_cream:',
    description: 'ICE_CREAM',
  },
  {
    type: 3,
    selected: false,
    image: '1f369.png',
    code_decimal: '&#127849;',
    title: ':doughnut:',
    description: 'DOUGHNUT',
  },
  {
    type: 3,
    selected: false,
    image: '1f36a.png',
    code_decimal: '&#127850;',
    title: ':cookie:',
    description: 'COOKIE',
  },
  {
    type: 3,
    selected: false,
    image: '1f36b.png',
    code_decimal: '&#127851;',
    title: ':chocolate_bar:',
    description: 'CHOCOLATE_BAR',
  },
  {
    type: 3,
    selected: false,
    image: '1f36c.png',
    code_decimal: '&#127852;',
    title: ':candy:',
    description: 'CANDY',
  },
  {
    type: 3,
    selected: false,
    image: '1f36d.png',
    code_decimal: '&#127853;',
    title: ':lollipop:',
    description: 'LOLLIPOP',
  },
  {
    type: 3,
    selected: false,
    image: '1f36e.png',
    code_decimal: '&#127854;',
    title: ':custard:',
    description: 'CUSTARD',
  },
  {
    type: 3,
    selected: false,
    image: '1f36f.png',
    code_decimal: '&#127855;',
    title: ':honey_pot:',
    description: 'HONEY_POT',
  },
  {
    type: 3,
    selected: false,
    image: '1f370.png',
    code_decimal: '&#127856;',
    title: ':cake:',
    description: 'CAKE',
  },
  {
    type: 3,
    selected: false,
    image: '1f371.png',
    code_decimal: '&#127857;',
    title: ':bento:',
    description: 'BENTO',
  },
  {
    type: 3,
    selected: false,
    image: '1f372.png',
    code_decimal: '&#127858;',
    title: ':stew:',
    description: 'STEW',
  },
  {
    type: 3,
    selected: false,
    image: '1f373.png',
    code_decimal: '&#127859;',
    title: ':egg:',
    description: 'EGG',
  },
  {
    type: 3,
    selected: false,
    image: '1f374.png',
    code_decimal: '&#127860;',
    title: ':fork_and_knife:',
    description: 'FORK_AND_KNIFE',
  },
  {
    type: 3,
    selected: false,
    image: '1f375.png',
    code_decimal: '&#127861;',
    title: ':tea:',
    description: 'TEA',
  },
  {
    type: 3,
    selected: false,
    image: '2615.png',
    code_decimal: '&#9749;',
    title: ':coffee:',
    description: 'COFFEE',
  },
  {
    type: 3,
    selected: false,
    image: '1f376.png',
    code_decimal: '&#127862;',
    title: ':sake:',
    description: 'SAKE',
  },
  {
    type: 3,
    selected: false,
    image: '1f377.png',
    code_decimal: '&#127863;',
    title: ':wine_glass:',
    description: 'WINE_GLASS',
  },
  {
    type: 3,
    selected: false,
    image: '1f378.png',
    code_decimal: '&#127864;',
    title: ':cocktail:',
    description: 'COCKTAIL',
  },
  {
    type: 3,
    selected: false,
    image: '1f379.png',
    code_decimal: '&#127865;',
    title: ':tropical_drink:',
    description: 'TROPICAL_DRINK',
  },
  {
    type: 3,
    selected: false,
    image: '1f37a.png',
    code_decimal: '&#127866;',
    title: ':beer:',
    description: 'BEER',
  },
  {
    type: 3,
    selected: false,
    image: '1f37b.png',
    code_decimal: '&#127867;',
    title: ':beers:',
    description: 'BEERS',
  },
  {
    type: 3,
    selected: false,
    image: '1f37c.png',
    code_decimal: '&#127868;',
    title: ':baby_bottle:',
    description: 'BABY_BOTTLE',
  },
];
export default jsonEmoji3;
