const jsonEmoji4 = [
  {
    type: 4,
    selected: false,
    image: '1f3c3.png',
    code_decimal: '&#127939;',
    title: ':runner:',
    description: 'RUNNER',
  },
  {
    type: 4,
    selected: false,
    image: '1f6b6.png',
    code_decimal: '&#128694;',
    title: ':walking:',
    description: 'WALKING',
  },
  {
    type: 4,
    selected: false,
    image: '1f483.png',
    code_decimal: '&#128131;',
    title: ':dancer:',
    description: 'DANCER',
  },
  {
    type: 4,
    selected: false,
    image: '1f3cb.png',
    code_decimal: '&#127947;',
    title: ':lifter:',
    description: 'LIFTER',
  },
  {
    type: 4,
    selected: false,
    image: '1f3cc.png',
    code_decimal: '&#127948;',
    title: ':golfer:',
    description: 'GOLFER',
  },
  {
    type: 4,
    selected: false,
    image: '1f6a3.png',
    code_decimal: '&#128675;',
    title: ':rowboat:',
    description: 'ROWBOAT',
  },
  {
    type: 4,
    selected: false,
    image: '1f3ca.png',
    code_decimal: '&#127946;',
    title: ':swimmer:',
    description: 'SWIMMER',
  },
  {
    type: 4,
    selected: false,
    image: '1f3c4.png',
    code_decimal: '&#127940;',
    title: ':surfer:',
    description: 'SURFER',
  },
  {
    type: 4,
    selected: false,
    image: '1f6c0.png',
    code_decimal: '&#128704;',
    title: ':bath:',
    description: 'BATH',
  },
  {
    type: 4,
    selected: false,
    image: '1f3c2.png',
    code_decimal: '&#127938;',
    title: ':snowboarder:',
    description: 'SNOWBOARDER',
  },
  {
    type: 4,
    selected: false,
    image: '1f3bf.png',
    code_decimal: '&#127935;',
    title: ':ski:',
    description: 'SKI',
  },
  {
    type: 4,
    selected: false,
    image: '26c4.png',
    code_decimal: '&#9924;',
    title: ':snowman:',
    description: 'SNOWMAN',
  },
  {
    type: 4,
    selected: false,
    image: '1f6b4.png',
    code_decimal: '&#128692;',
    title: ':bicyclist:',
    description: 'BICYCLIST',
  },
  {
    type: 4,
    selected: false,
    image: '1f6b5.png',
    code_decimal: '&#128693;',
    title: ':mountain_bicyclist:',
    description: 'MOUNTAIN_BICYCLIST',
  },
  {
    type: 4,
    selected: false,
    image: '1f3cd.png',
    code_decimal: '&#127949;',
    title: ':motorcycle:',
    description: 'MOTORCYCLE',
  },
  {
    type: 4,
    selected: false,
    image: '1f3ce.png',
    code_decimal: '&#127950;',
    title: ':race_car:',
    description: 'RACE_CAR',
  },
  {
    type: 4,
    selected: false,
    image: '1f3c7.png',
    code_decimal: '&#127943;',
    title: ':horse_racing:',
    description: 'HORSE_RACING',
  },
  {
    type: 4,
    selected: false,
    image: '26fa.png',
    code_decimal: '&#9978;',
    title: ':tent:',
    description: 'TENT',
  },
  {
    type: 4,
    selected: false,
    image: '1f3a3.png',
    code_decimal: '&#127907;',
    title: ':fishing_pole_and_fish:',
    description: 'FISHING_POLE_AND_FISH',
  },
  {
    type: 4,
    selected: false,
    image: '26bd.png',
    code_decimal: '&#9917;',
    title: ':soccer:',
    description: 'SOCCER',
  },
  {
    type: 4,
    selected: false,
    image: '1f3c0.png',
    code_decimal: '&#127936;',
    title: ':basketball:',
    description: 'BASKETBALL',
  },
  {
    type: 4,
    selected: false,
    image: '1f3c8.png',
    code_decimal: '&#127944;',
    title: ':football:',
    description: 'FOOTBALL',
  },
  {
    type: 4,
    selected: false,
    image: '26be.png',
    code_decimal: '&#9918;',
    title: ':baseball:',
    description: 'BASEBALL',
  },
  {
    type: 4,
    selected: false,
    image: '1f3be.png',
    code_decimal: '&#127934;',
    title: ':tennis:',
    description: 'TENNIS',
  },
  {
    type: 4,
    selected: false,
    image: '1f3c9.png',
    code_decimal: '&#127945;',
    title: ':rugby_football:',
    description: 'RUGBY_FOOTBALL',
  },
  {
    type: 4,
    selected: false,
    image: '26f3.png',
    code_decimal: '&#9971;',
    title: ':golf:',
    description: 'GOLF',
  },
  {
    type: 4,
    selected: false,
    image: '1f3c6.png',
    code_decimal: '&#127942;',
    title: ':trophy:',
    description: 'TROPHY',
  },
  {
    type: 4,
    selected: false,
    image: '1f3c5.png',
    code_decimal: '&#127941;',
    title: ':medal:',
    description: 'MEDAL',
  },
  {
    type: 4,
    selected: false,
    image: '1f3bd.png',
    code_decimal: '&#127933;',
    title: ':running_shirt_with_sash:',
    description: 'RUNNING_SHIRT_WITH_SASH',
  },
  {
    type: 4,
    selected: false,
    image: '1f3c1.png',
    code_decimal: '&#127937;',
    title: ':checkered_flag:',
    description: 'CHECKERED_FLAG',
  },
  {
    type: 4,
    selected: false,
    image: '1f3b9.png',
    code_decimal: '&#127929;',
    title: ':musical_keyboard:',
    description: 'MUSICAL_KEYBOARD',
  },
  {
    type: 4,
    selected: false,
    image: '1f3b8.png',
    code_decimal: '&#127928;',
    title: ':guitar:',
    description: 'GUITAR',
  },
  {
    type: 4,
    selected: false,
    image: '1f3bb.png',
    code_decimal: '&#127931;',
    title: ':violin:',
    description: 'VIOLIN',
  },
  {
    type: 4,
    selected: false,
    image: '1f3b7.png',
    code_decimal: '&#127927;',
    title: ':saxophone:',
    description: 'SAXOPHONE',
  },
  {
    type: 4,
    selected: false,
    image: '1f3ba.png',
    code_decimal: '&#127930;',
    title: ':trumpet:',
    description: 'TRUMPET',
  },
  {
    type: 4,
    selected: false,
    image: '1f3b5.png',
    code_decimal: '&#127925;',
    title: ':musical_note:',
    description: 'MUSICAL_NOTE',
  },
  {
    type: 4,
    selected: false,
    image: '1f3b6.png',
    code_decimal: '&#127926;',
    title: ':notes:',
    description: 'NOTES',
  },
  {
    type: 4,
    selected: false,
    image: '1f3bc.png',
    code_decimal: '&#127932;',
    title: ':musical_score:',
    description: 'MUSICAL_SCORE',
  },
  {
    type: 4,
    selected: false,
    image: '1f3a7.png',
    code_decimal: '&#127911;',
    title: ':headphones:',
    description: 'HEADPHONES',
  },
  {
    type: 4,
    selected: false,
    image: '1f3a4.png',
    code_decimal: '&#127908;',
    title: ':microphone:',
    description: 'MICROPHONE',
  },
  {
    type: 4,
    selected: false,
    image: '1f3ad.png',
    code_decimal: '&#127917;',
    title: ':performing_arts:',
    description: 'PERFORMING_ARTS',
  },
  {
    type: 4,
    selected: false,
    image: '1f3ab.png',
    code_decimal: '&#127915;',
    title: ':ticket:',
    description: 'TICKET',
  },
  {
    type: 4,
    selected: false,
    image: '1f3a9.png',
    code_decimal: '&#127913;',
    title: ':tophat:',
    description: 'TOPHAT',
  },
  {
    type: 4,
    selected: false,
    image: '1f3aa.png',
    code_decimal: '&#127914;',
    title: ':circus_tent:',
    description: 'CIRCUS_TENT',
  },
  {
    type: 4,
    selected: false,
    image: '1f3ac.png',
    code_decimal: '&#127916;',
    title: ':clapper:',
    description: 'CLAPPER',
  },
  {
    type: 4,
    selected: false,
    image: '1f39e.png',
    code_decimal: '&#127902;',
    title: ':film_frames:',
    description: 'FILM_FRAMES',
  },
  {
    type: 4,
    selected: false,
    image: '1f39f.png',
    code_decimal: '&#127903;',
    title: ':tickets:',
    description: 'TICKETS',
  },
  {
    type: 4,
    selected: false,
    image: '1f3a8.png',
    code_decimal: '&#127912;',
    title: ':art:',
    description: 'ART',
  },
  {
    type: 4,
    selected: false,
    image: '1f3af.png',
    code_decimal: '&#127919;',
    title: ':dart:',
    description: 'DART',
  },
  {
    type: 4,
    selected: false,
    image: '1f3b1.png',
    code_decimal: '&#127921;',
    title: ':8ball:',
    description: '8BALL',
  },
  {
    type: 4,
    selected: false,
    image: '1f3b3.png',
    code_decimal: '&#127923;',
    title: ':bowling:',
    description: 'BOWLING',
  },
  {
    type: 4,
    selected: false,
    image: '1f3b0.png',
    code_decimal: '&#127920;',
    title: ':slot_machine:',
    description: 'SLOT_MACHINE',
  },
  {
    type: 4,
    selected: false,
    image: '1f3b2.png',
    code_decimal: '&#127922;',
    title: ':game_die:',
    description: 'GAME_DIE',
  },
  {
    type: 4,
    selected: false,
    image: '1f3ae.png',
    code_decimal: '&#127918;',
    title: ':video_game:',
    description: 'VIDEO_GAME',
  },
  {
    type: 4,
    selected: false,
    image: '1f3b4.png',
    code_decimal: '&#127924;',
    title: ':flower_playing_cards:',
    description: 'FLOWER_PLAYING_CARDS',
  },
  {
    type: 4,
    selected: false,
    image: '1f0cf.png',
    code_decimal: '&#127183;',
    title: ':black_joker:',
    description: 'BLACK_JOKER',
  },
  {
    type: 4,
    selected: false,
    image: '1f004.png',
    code_decimal: '&#126980;',
    title: ':mahjong:',
    description: 'MAHJONG',
  },
  {
    type: 4,
    selected: false,
    image: '1f3a0.png',
    code_decimal: '&#127904;',
    title: ':carousel_horse:',
    description: 'CAROUSEL_HORSE',
  },
  {
    type: 4,
    selected: false,
    image: '1f3a1.png',
    code_decimal: '&#127905;',
    title: ':ferris_wheel:',
    description: 'FERRIS_WHEEL',
  },
  {
    type: 4,
    selected: false,
    image: '1f3a2.png',
    code_decimal: '&#127906;',
    title: ':roller_coaster:',
    description: 'ROLLER_COASTER',
  },
];
export default jsonEmoji4;
