const jsonEmoji5 = [
  {
    type: 5,
    selected: false,
    image: '1f683.png',
    code_decimal: '&#128643;',
    title: ':railway_car:',
    description: 'RAILWAY_CAR',
  },
  {
    type: 5,
    selected: false,
    image: '1f69e.png',
    code_decimal: '&#128670;',
    title: ':mountain_railway:',
    description: 'MOUNTAIN_RAILWAY',
  },
  {
    type: 5,
    selected: false,
    image: '1f682.png',
    code_decimal: '&#128642;',
    title: ':steam_locomotive:',
    description: 'STEAM_LOCOMOTIVE',
  },
  {
    type: 5,
    selected: false,
    image: '1f68b.png',
    code_decimal: '&#128651;',
    title: ':train:',
    description: 'TRAIN',
  },
  {
    type: 5,
    selected: false,
    image: '1f69d.png',
    code_decimal: '&#128669;',
    title: ':monorail:',
    description: 'MONORAIL',
  },
  {
    type: 5,
    selected: false,
    image: '1f684.png',
    code_decimal: '&#128644;',
    title: ':bullettrain_side:',
    description: 'BULLETTRAIN_SIDE',
  },
  {
    type: 5,
    selected: false,
    image: '1f685.png',
    code_decimal: '&#128645;',
    title: ':bullettrain_front:',
    description: 'BULLETTRAIN_FRONT',
  },
  {
    type: 5,
    selected: false,
    image: '1f686.png',
    code_decimal: '&#128646;',
    title: ':train2:',
    description: 'TRAIN2',
  },
  {
    type: 5,
    selected: false,
    image: '1f687.png',
    code_decimal: '&#128647;',
    title: ':metro:',
    description: 'METRO',
  },
  {
    type: 5,
    selected: false,
    image: '1f688.png',
    code_decimal: '&#128648;',
    title: ':light_rail:',
    description: 'LIGHT_RAIL',
  },
  {
    type: 5,
    selected: false,
    image: '1f689.png',
    code_decimal: '&#128649;',
    title: ':station:',
    description: 'STATION',
  },
  {
    type: 5,
    selected: false,
    image: '1f68a.png',
    code_decimal: '&#128650;',
    title: ':tram:',
    description: 'TRAM',
  },
  {
    type: 5,
    selected: false,
    image: '1f6e4.png',
    code_decimal: '&#128740;',
    title: ':railway_track:',
    description: 'RAILWAY_TRACK',
  },
  {
    type: 5,
    selected: false,
    image: '1f68c.png',
    code_decimal: '&#128652;',
    title: ':bus:',
    description: 'BUS',
  },
  {
    type: 5,
    selected: false,
    image: '1f68d.png',
    code_decimal: '&#128653;',
    title: ':oncoming_bus:',
    description: 'ONCOMING_BUS',
  },
  {
    type: 5,
    selected: false,
    image: '1f68e.png',
    code_decimal: '&#128654;',
    title: ':trolleybus:',
    description: 'TROLLEYBUS',
  },
  {
    type: 5,
    selected: false,
    image: '1f690.png',
    code_decimal: '&#128656;',
    title: ':minibus:',
    description: 'MINIBUS',
  },
  {
    type: 5,
    selected: false,
    image: '1f691.png',
    code_decimal: '&#128657;',
    title: ':ambulance:',
    description: 'AMBULANCE',
  },
  {
    type: 5,
    selected: false,
    image: '1f692.png',
    code_decimal: '&#128658;',
    title: ':fire_engine:',
    description: 'FIRE_ENGINE',
  },
  {
    type: 5,
    selected: false,
    image: '1f693.png',
    code_decimal: '&#128659;',
    title: ':police_car:',
    description: 'POLICE_CAR',
  },
  {
    type: 5,
    selected: false,
    image: '1f694.png',
    code_decimal: '&#128660;',
    title: ':oncoming_police_car:',
    description: 'ONCOMING_POLICE_CAR',
  },
  {
    type: 5,
    selected: false,
    image: '1f6a8.png',
    code_decimal: '&#128680;',
    title: ':rotating_light:',
    description: 'ROTATING_LIGHT',
  },
  {
    type: 5,
    selected: false,
    image: '1f695.png',
    code_decimal: '&#128661;',
    title: ':taxi:',
    description: 'TAXI',
  },
  {
    type: 5,
    selected: false,
    image: '1f696.png',
    code_decimal: '&#128662;',
    title: ':oncoming_taxi:',
    description: 'ONCOMING_TAXI',
  },
  {
    type: 5,
    selected: false,
    image: '1f697.png',
    code_decimal: '&#128663;',
    title: ':red_car:',
    description: 'RED_CAR',
  },
  {
    type: 5,
    selected: false,
    image: '1f698.png',
    code_decimal: '&#128664;',
    title: ':oncoming_automobile:',
    description: 'ONCOMING_AUTOMOBILE',
  },
  {
    type: 5,
    selected: false,
    image: '1f699.png',
    code_decimal: '&#128665;',
    title: ':blue_car:',
    description: 'BLUE_CAR',
  },
  {
    type: 5,
    selected: false,
    image: '1f69a.png',
    code_decimal: '&#128666;',
    title: ':truck:',
    description: 'TRUCK',
  },
  {
    type: 5,
    selected: false,
    image: '1f69b.png',
    code_decimal: '&#128667;',
    title: ':articulated_lorry:',
    description: 'ARTICULATED_LORRY',
  },
  {
    type: 5,
    selected: false,
    image: '1f69c.png',
    code_decimal: '&#128668;',
    title: ':tractor:',
    description: 'TRACTOR',
  },
  {
    type: 5,
    selected: false,
    image: '1f6b2.png',
    code_decimal: '&#128690;',
    title: ':bike:',
    description: 'BIKE',
  },
  {
    type: 5,
    selected: false,
    image: '1f6e3.png',
    code_decimal: '&#128739;',
    title: ':motorway:',
    description: 'MOTORWAY',
  },
  {
    type: 5,
    selected: false,
    image: '1f68f.png',
    code_decimal: '&#128655;',
    title: ':busstop:',
    description: 'BUSSTOP',
  },
  {
    type: 5,
    selected: false,
    image: '26fd.png',
    code_decimal: '&#9981;',
    title: ':fuelpump:',
    description: 'FUELPUMP',
  },
  {
    type: 5,
    selected: false,
    image: '1f6a7.png',
    code_decimal: '&#128679;',
    title: ':construction:',
    description: 'CONSTRUCTION',
  },
  {
    type: 5,
    selected: false,
    image: '1f6a6.png',
    code_decimal: '&#128678;',
    title: ':vertical_traffic_light:',
    description: 'VERTICAL_TRAFFIC_LIGHT',
  },
  {
    type: 5,
    selected: false,
    image: '1f6a5.png',
    code_decimal: '&#128677;',
    title: ':traffic_light:',
    description: 'TRAFFIC_LIGHT',
  },
  {
    type: 5,
    selected: false,
    image: '1f680.png',
    code_decimal: '&#128640;',
    title: ':rocket:',
    description: 'ROCKET',
  },
  {
    type: 5,
    selected: false,
    image: '1f681.png',
    code_decimal: '&#128641;',
    title: ':helicopter:',
    description: 'HELICOPTER',
  },
  {
    type: 5,
    selected: false,
    image: '2708.png',
    code_decimal: '&#9992;',
    title: ':airplane:',
    description: 'AIRPLANE',
  },
  {
    type: 5,
    selected: false,
    image: '1f6e9.png',
    code_decimal: '&#128745;',
    title: ':airplane_small:',
    description: 'AIRPLANE_SMALL',
  },
  {
    type: 5,
    selected: false,
    image: '1f6eb.png',
    code_decimal: '&#128747;',
    title: ':airplane_departure:',
    description: 'AIRPLANE_DEPARTURE',
  },
  {
    type: 5,
    selected: false,
    image: '1f6ec.png',
    code_decimal: '&#128748;',
    title: ':airplane_arriving:',
    description: 'AIRPLANE_ARRIVING',
  },
  {
    type: 5,
    selected: false,
    image: '1f4ba.png',
    code_decimal: '&#128186;',
    title: ':seat:',
    description: 'SEAT',
  },
  {
    type: 5,
    selected: false,
    image: '2693.png',
    code_decimal: '&#9875;',
    title: ':anchor:',
    description: 'ANCHOR',
  },
  {
    type: 5,
    selected: false,
    image: '1f6a2.png',
    code_decimal: '&#128674;',
    title: ':ship:',
    description: 'SHIP',
  },
  {
    type: 5,
    selected: false,
    image: '1f6f3.png',
    code_decimal: '&#128755;',
    title: ':cruise_ship:',
    description: 'CRUISE_SHIP',
  },
  {
    type: 5,
    selected: false,
    image: '1f6e5.png',
    code_decimal: '&#128741;',
    title: ':motorboat:',
    description: 'MOTORBOAT',
  },
  {
    type: 5,
    selected: false,
    image: '1f6a4.png',
    code_decimal: '&#128676;',
    title: ':speedboat:',
    description: 'SPEEDBOAT',
  },
  {
    type: 5,
    selected: false,
    image: '26f5.png',
    code_decimal: '&#9973;',
    title: ':sailboat:',
    description: 'SAILBOAT',
  },
  {
    type: 5,
    selected: false,
    image: '1f6a1.png',
    code_decimal: '&#128673;',
    title: ':aerial_tramway:',
    description: 'AERIAL_TRAMWAY',
  },
  {
    type: 5,
    selected: false,
    image: '1f6a0.png',
    code_decimal: '&#128672;',
    title: ':mountain_cableway:',
    description: 'MOUNTAIN_CABLEWAY',
  },
  {
    type: 5,
    selected: false,
    image: '1f69f.png',
    code_decimal: '&#128671;',
    title: ':suspension_railway:',
    description: 'SUSPENSION_RAILWAY',
  },
  {
    type: 5,
    selected: false,
    image: '1f6c2.png',
    code_decimal: '&#128706;',
    title: ':passport_control:',
    description: 'PASSPORT_CONTROL',
  },
  {
    type: 5,
    selected: false,
    image: '1f6c3.png',
    code_decimal: '&#128707;',
    title: ':customs:',
    description: 'CUSTOMS',
  },
  {
    type: 5,
    selected: false,
    image: '1f6c4.png',
    code_decimal: '&#128708;',
    title: ':baggage_claim:',
    description: 'BAGGAGE_CLAIM',
  },
  {
    type: 5,
    selected: false,
    image: '1f6c5.png',
    code_decimal: '&#128709;',
    title: ':left_luggage:',
    description: 'LEFT_LUGGAGE',
  },
  {
    type: 5,
    selected: false,
    image: '1f4b4.png',
    code_decimal: '&#128180;',
    title: ':yen:',
    description: 'YEN',
  },
  {
    type: 5,
    selected: false,
    image: '1f4b6.png',
    code_decimal: '&#128182;',
    title: ':euro:',
    description: 'EURO',
  },
  {
    type: 5,
    selected: false,
    image: '1f4b7.png',
    code_decimal: '&#128183;',
    title: ':pound:',
    description: 'POUND',
  },
  {
    type: 5,
    selected: false,
    image: '1f4b5.png',
    code_decimal: '&#128181;',
    title: ':dollar:',
    description: 'DOLLAR',
  },
  {
    type: 5,
    selected: false,
    image: '1f6ce.png',
    code_decimal: '&#128718;',
    title: ':bellhop:',
    description: 'BELLHOP',
  },
  {
    type: 5,
    selected: false,
    image: '1f6cf.png',
    code_decimal: '&#128719;',
    title: ':bed:',
    description: 'BED',
  },
  {
    type: 5,
    selected: false,
    image: '1f6cb.png',
    code_decimal: '&#128715;',
    title: ':couch:',
    description: 'COUCH',
  },
  {
    type: 5,
    selected: false,
    image: '1f37d.png',
    code_decimal: '&#127869;',
    title: ':fork_knife_plate:',
    description: 'FORK_KNIFE_PLATE',
  },
  {
    type: 5,
    selected: false,
    image: '1f6cd.png',
    code_decimal: '&#128717;',
    title: ':shopping_bags:',
    description: 'SHOPPING_BAGS',
  },
  {
    type: 5,
    selected: false,
    image: '1f5fd.png',
    code_decimal: '&#128509;',
    title: ':statue_of_liberty:',
    description: 'STATUE_OF_LIBERTY',
  },
  {
    type: 5,
    selected: false,
    image: '1f5ff.png',
    code_decimal: '&#128511;',
    title: ':moyai:',
    description: 'MOYAI',
  },
  {
    type: 5,
    selected: false,
    image: '1f301.png',
    code_decimal: '&#127745;',
    title: ':foggy:',
    description: 'FOGGY',
  },
  {
    type: 5,
    selected: false,
    image: '1f5fc.png',
    code_decimal: '&#128508;',
    title: ':tokyo_tower:',
    description: 'TOKYO_TOWER',
  },
  {
    type: 5,
    selected: false,
    image: '26f2.png',
    code_decimal: '&#9970;',
    title: ':fountain:',
    description: 'FOUNTAIN',
  },
  {
    type: 5,
    selected: false,
    image: '1f3f0.png',
    code_decimal: '&#127984;',
    title: ':european_castle:',
    description: 'EUROPEAN_CASTLE',
  },
  {
    type: 5,
    selected: false,
    image: '1f3ef.png',
    code_decimal: '&#127983;',
    title: ':japanese_castle:',
    description: 'JAPANESE_CASTLE',
  },
  {
    type: 5,
    selected: false,
    image: '1f3db.png',
    code_decimal: '&#127963;',
    title: ':classical_building:',
    description: 'CLASSICAL_BUILDING',
  },
  {
    type: 5,
    selected: false,
    image: '1f3df.png',
    code_decimal: '&#127967;',
    title: ':stadium:',
    description: 'STADIUM',
  },
  {
    type: 5,
    selected: false,
    image: '1f3d4.png',
    code_decimal: '&#127956;',
    title: ':mountain_snow:',
    description: 'MOUNTAIN_SNOW',
  },
  {
    type: 5,
    selected: false,
    image: '1f3d5.png',
    code_decimal: '&#127957;',
    title: ':camping:',
    description: 'CAMPING',
  },
  {
    type: 5,
    selected: false,
    image: '1f3d6.png',
    code_decimal: '&#127958;',
    title: ':beach:',
    description: 'BEACH',
  },
  {
    type: 5,
    selected: false,
    image: '1f3dc.png',
    code_decimal: '&#127964;',
    title: ':desert:',
    description: 'DESERT',
  },
  {
    type: 5,
    selected: false,
    image: '1f3dd.png',
    code_decimal: '&#127965;',
    title: ':island:',
    description: 'ISLAND',
  },
  {
    type: 5,
    selected: false,
    image: '1f3de.png',
    code_decimal: '&#127966;',
    title: ':park:',
    description: 'PARK',
  },
  {
    type: 5,
    selected: false,
    image: '1f3d9.png',
    code_decimal: '&#127961;',
    title: ':cityscape:',
    description: 'CITYSCAPE',
  },
  {
    type: 5,
    selected: false,
    image: '1f307.png',
    code_decimal: '&#127751;',
    title: ':city_sunset:',
    description: 'CITY_SUNSET',
  },
  {
    type: 5,
    selected: false,
    image: '1f306.png',
    code_decimal: '&#127750;',
    title: ':city_dusk:',
    description: 'CITY_DUSK',
  },
  {
    type: 5,
    selected: false,
    image: '1f303.png',
    code_decimal: '&#127747;',
    title: ':night_with_stars:',
    description: 'NIGHT_WITH_STARS',
  },
  {
    type: 5,
    selected: false,
    image: '1f309.png',
    code_decimal: '&#127753;',
    title: ':bridge_at_night:',
    description: 'BRIDGE_AT_NIGHT',
  },
  {
    type: 5,
    selected: false,
    image: '1f3e0.png',
    code_decimal: '&#127968;',
    title: ':house:',
    description: 'HOUSE',
  },
  {
    type: 5,
    selected: false,
    image: '1f3d8.png',
    code_decimal: '&#127960;',
    title: ':homes:',
    description: 'HOMES',
  },
  {
    type: 5,
    selected: false,
    image: '1f3e1.png',
    code_decimal: '&#127969;',
    title: ':house_with_garden:',
    description: 'HOUSE_WITH_GARDEN',
  },
  {
    type: 5,
    selected: false,
    image: '1f3da.png',
    code_decimal: '&#127962;',
    title: ':house_abandoned:',
    description: 'HOUSE_ABANDONED',
  },
  {
    type: 5,
    selected: false,
    image: '1f3d7.png',
    code_decimal: '&#127959;',
    title: ':contruction_site:',
    description: 'CONTRUCTION_SITE',
  },
  {
    type: 5,
    selected: false,
    image: '1f3e2.png',
    code_decimal: '&#127970;',
    title: ':office:',
    description: 'OFFICE',
  },
  {
    type: 5,
    selected: false,
    image: '1f3ec.png',
    code_decimal: '&#127980;',
    title: ':department_store:',
    description: 'DEPARTMENT_STORE',
  },
  {
    type: 5,
    selected: false,
    image: '1f3ed.png',
    code_decimal: '&#127981;',
    title: ':factory:',
    description: 'FACTORY',
  },
  {
    type: 5,
    selected: false,
    image: '1f3e3.png',
    code_decimal: '&#127971;',
    title: ':post_office:',
    description: 'POST_OFFICE',
  },
  {
    type: 5,
    selected: false,
    image: '1f3e4.png',
    code_decimal: '&#127972;',
    title: ':european_post_office:',
    description: 'EUROPEAN_POST_OFFICE',
  },
  {
    type: 5,
    selected: false,
    image: '1f3e5.png',
    code_decimal: '&#127973;',
    title: ':hospital:',
    description: 'HOSPITAL',
  },
  {
    type: 5,
    selected: false,
    image: '1f3e6.png',
    code_decimal: '&#127974;',
    title: ':bank:',
    description: 'BANK',
  },
  {
    type: 5,
    selected: false,
    image: '1f3e8.png',
    code_decimal: '&#127976;',
    title: ':hotel:',
    description: 'HOTEL',
  },
  {
    type: 5,
    selected: false,
    image: '1f3e9.png',
    code_decimal: '&#127977;',
    title: ':love_hotel:',
    description: 'LOVE_HOTEL',
  },
  {
    type: 5,
    selected: false,
    image: '1f492.png',
    code_decimal: '&#128146;',
    title: ':wedding:',
    description: 'WEDDING',
  },
  {
    type: 5,
    selected: false,
    image: '26ea.png',
    code_decimal: '&#9962;',
    title: ':church:',
    description: 'CHURCH',
  },
  {
    type: 5,
    selected: false,
    image: '1f3ea.png',
    code_decimal: '&#127978;',
    title: ':convenience_store:',
    description: 'CONVENIENCE_STORE',
  },
  {
    type: 5,
    selected: false,
    image: '1f3eb.png',
    code_decimal: '&#127979;',
    title: ':school:',
    description: 'SCHOOL',
  },
  {
    type: 5,
    selected: false,
    image: '1f5fa.png',
    code_decimal: '&#128506;',
    title: ':map:',
    description: 'MAP',
  },
];
export default jsonEmoji5;
