const jsonEmoji6 = [
  {
    type: 6,
    selected: false,
    image: '1f380.png',
    code_decimal: '&#127872;',
    title: ':ribbon:',
    description: 'RIBBON',
  },
  {
    type: 6,
    selected: false,
    image: '1f381.png',
    code_decimal: '&#127873;',
    title: ':gift:',
    description: 'GIFT',
  },
  {
    type: 6,
    selected: false,
    image: '1f382.png',
    code_decimal: '&#127874;',
    title: ':birthday:',
    description: 'BIRTHDAY',
  },
  {
    type: 6,
    selected: false,
    image: '1f383.png',
    code_decimal: '&#127875;',
    title: ':jack_o_lantern:',
    description: 'JACK_O_LANTERN',
  },
  {
    type: 6,
    selected: false,
    image: '1f384.png',
    code_decimal: '&#127876;',
    title: ':christmas_tree:',
    description: 'CHRISTMAS_TREE',
  },
  {
    type: 6,
    selected: false,
    image: '1f38b.png',
    code_decimal: '&#127883;',
    title: ':tanabata_tree:',
    description: 'TANABATA_TREE',
  },
  {
    type: 6,
    selected: false,
    image: '1f38d.png',
    code_decimal: '&#127885;',
    title: ':bamboo:',
    description: 'BAMBOO',
  },
  {
    type: 6,
    selected: false,
    image: '1f391.png',
    code_decimal: '&#127889;',
    title: ':rice_scene:',
    description: 'RICE_SCENE',
  },
  {
    type: 6,
    selected: false,
    image: '1f386.png',
    code_decimal: '&#127878;',
    title: ':fireworks:',
    description: 'FIREWORKS',
  },
  {
    type: 6,
    selected: false,
    image: '1f387.png',
    code_decimal: '&#127879;',
    title: ':sparkler:',
    description: 'SPARKLER',
  },
  {
    type: 6,
    selected: false,
    image: '1f389.png',
    code_decimal: '&#127881;',
    title: ':tada:',
    description: 'TADA',
  },
  {
    type: 6,
    selected: false,
    image: '1f38a.png',
    code_decimal: '&#127882;',
    title: ':confetti_ball:',
    description: 'CONFETTI_BALL',
  },
  {
    type: 6,
    selected: false,
    image: '1f388.png',
    code_decimal: '&#127880;',
    title: ':balloon:',
    description: 'BALLOON',
  },
  {
    type: 6,
    selected: false,
    image: '1f4ab.png',
    code_decimal: '&#128171;',
    title: ':dizzy:',
    description: 'DIZZY',
  },
  {
    type: 6,
    selected: false,
    image: '2728.png',
    code_decimal: '&#10024;',
    title: ':sparkles:',
    description: 'SPARKLES',
  },
  {
    type: 6,
    selected: false,
    image: '1f4a5.png',
    code_decimal: '&#128165;',
    title: ':boom:',
    description: 'BOOM',
  },
  {
    type: 6,
    selected: false,
    image: '1f393.png',
    code_decimal: '&#127891;',
    title: ':mortar_board:',
    description: 'MORTAR_BOARD',
  },
  {
    type: 6,
    selected: false,
    image: '1f451.png',
    code_decimal: '&#128081;',
    title: ':crown:',
    description: 'CROWN',
  },
  {
    type: 6,
    selected: false,
    image: '1f397.png',
    code_decimal: '&#127895;',
    title: ':reminder_ribbon:',
    description: 'REMINDER_RIBBON',
  },
  {
    type: 6,
    selected: false,
    image: '1f396.png',
    code_decimal: '&#127894;',
    title: ':military_medal:',
    description: 'MILITARY_MEDAL',
  },
  {
    type: 6,
    selected: false,
    image: '1f38e.png',
    code_decimal: '&#127886;',
    title: ':dolls:',
    description: 'DOLLS',
  },
  {
    type: 6,
    selected: false,
    image: '1f38f.png',
    code_decimal: '&#127887;',
    title: ':flags:',
    description: 'FLAGS',
  },
  {
    type: 6,
    selected: false,
    image: '1f390.png',
    code_decimal: '&#127888;',
    title: ':wind_chime:',
    description: 'WIND_CHIME',
  },
  {
    type: 6,
    selected: false,
    image: '1f38c.png',
    code_decimal: '&#127884;',
    title: ':crossed_flags:',
    description: 'CROSSED_FLAGS',
  },
  {
    type: 6,
    selected: false,
    image: '1f3ee.png',
    code_decimal: '&#127982;',
    title: ':izakaya_lantern:',
    description: 'IZAKAYA_LANTERN',
  },
  {
    type: 6,
    selected: false,
    image: '1f48d.png',
    code_decimal: '&#128141;',
    title: ':ring:',
    description: 'RING',
  },
  {
    type: 6,
    selected: false,
    image: '2764.png',
    code_decimal: '&#10084;',
    title: ':heart:',
    description: 'HEART',
  },
  {
    type: 6,
    selected: false,
    image: '1f494.png',
    code_decimal: '&#128148;',
    title: ':broken_heart:',
    description: 'BROKEN_HEART',
  },
  {
    type: 6,
    selected: false,
    image: '1f48c.png',
    code_decimal: '&#128140;',
    title: ':love_letter:',
    description: 'LOVE_LETTER',
  },
  {
    type: 6,
    selected: false,
    image: '1f495.png',
    code_decimal: '&#128149;',
    title: ':two_hearts:',
    description: 'TWO_HEARTS',
  },
  {
    type: 6,
    selected: false,
    image: '1f49e.png',
    code_decimal: '&#128158;',
    title: ':revolving_hearts:',
    description: 'REVOLVING_HEARTS',
  },
  {
    type: 6,
    selected: false,
    image: '1f493.png',
    code_decimal: '&#128147;',
    title: ':heartbeat:',
    description: 'HEARTBEAT',
  },
  {
    type: 6,
    selected: false,
    image: '1f497.png',
    code_decimal: '&#128151;',
    title: ':heartpulse:',
    description: 'HEARTPULSE',
  },
  {
    type: 6,
    selected: false,
    image: '1f496.png',
    code_decimal: '&#128150;',
    title: ':sparkling_heart:',
    description: 'SPARKLING_HEART',
  },
  {
    type: 6,
    selected: false,
    image: '1f498.png',
    code_decimal: '&#128152;',
    title: ':cupid:',
    description: 'CUPID',
  },
  {
    type: 6,
    selected: false,
    image: '1f49d.png',
    code_decimal: '&#128157;',
    title: ':gift_heart:',
    description: 'GIFT_HEART',
  },
  {
    type: 6,
    selected: false,
    image: '1f49f.png',
    code_decimal: '&#128159;',
    title: ':heart_decoration:',
    description: 'HEART_DECORATION',
  },
  {
    type: 6,
    selected: false,
    image: '1f49c.png',
    code_decimal: '&#128156;',
    title: ':purple_heart:',
    description: 'PURPLE_HEART',
  },
  {
    type: 6,
    selected: false,
    image: '1f49b.png',
    code_decimal: '&#128155;',
    title: ':yellow_heart:',
    description: 'YELLOW_HEART',
  },
  {
    type: 6,
    selected: false,
    image: '1f49a.png',
    code_decimal: '&#128154;',
    title: ':green_heart:',
    description: 'GREEN_HEART',
  },
  {
    type: 6,
    selected: false,
    image: '1f499.png',
    code_decimal: '&#128153;',
    title: ':blue_heart:',
    description: 'BLUE_HEART',
  },
];
export default jsonEmoji6;
