const jsonEmoji2 = [
  {
    type: 2,
    selected: false,
    image: '1f331.png',
    code_decimal: '&#127793;',
    title: ':seedling:',
    description: 'SEEDLING',
  },
  {
    type: 2,
    selected: false,
    image: '1f332.png',
    code_decimal: '&#127794;',
    title: ':evergreen_tree:',
    description: 'EVERGREEN_TREE',
  },
  {
    type: 2,
    selected: false,
    image: '1f333.png',
    code_decimal: '&#127795;',
    title: ':deciduous_tree:',
    description: 'DECIDUOUS_TREE',
  },
  {
    type: 2,
    selected: false,
    image: '1f334.png',
    code_decimal: '&#127796;',
    title: ':palm_tree:',
    description: 'PALM_TREE',
  },
  {
    type: 2,
    selected: false,
    image: '1f335.png',
    code_decimal: '&#127797;',
    title: ':cactus:',
    description: 'CACTUS',
  },
  {
    type: 2,
    selected: false,
    image: '1f337.png',
    code_decimal: '&#127799;',
    title: ':tulip:',
    description: 'TULIP',
  },
  {
    type: 2,
    selected: false,
    image: '1f338.png',
    code_decimal: '&#127800;',
    title: ':cherry_blossom:',
    description: 'CHERRY_BLOSSOM',
  },
  {
    type: 2,
    selected: false,
    image: '1f339.png',
    code_decimal: '&#127801;',
    title: ':rose:',
    description: 'ROSE',
  },
  {
    type: 2,
    selected: false,
    image: '1f33a.png',
    code_decimal: '&#127802;',
    title: ':hibiscus:',
    description: 'HIBISCUS',
  },
  {
    type: 2,
    selected: false,
    image: '1f33b.png',
    code_decimal: '&#127803;',
    title: ':sunflower:',
    description: 'SUNFLOWER',
  },
  {
    type: 2,
    selected: false,
    image: '1f33c.png',
    code_decimal: '&#127804;',
    title: ':blossom:',
    description: 'BLOSSOM',
  },
  {
    type: 2,
    selected: false,
    image: '1f490.png',
    code_decimal: '&#128144;',
    title: ':bouquet:',
    description: 'BOUQUET',
  },
  {
    type: 2,
    selected: false,
    image: '1f33e.png',
    code_decimal: '&#127806;',
    title: ':ear_of_rice:',
    description: 'EAR_OF_RICE',
  },
  {
    type: 2,
    selected: false,
    image: '1f33f.png',
    code_decimal: '&#127807;',
    title: ':herb:',
    description: 'HERB',
  },
  {
    type: 2,
    selected: false,
    image: '1f340.png',
    code_decimal: '&#127808;',
    title: ':four_leaf_clover:',
    description: 'FOUR_LEAF_CLOVER',
  },
  {
    type: 2,
    selected: false,
    image: '1f341.png',
    code_decimal: '&#127809;',
    title: ':maple_leaf:',
    description: 'MAPLE_LEAF',
  },
  {
    type: 2,
    selected: false,
    image: '1f342.png',
    code_decimal: '&#127810;',
    title: ':fallen_leaf:',
    description: 'FALLEN_LEAF',
  },
  {
    type: 2,
    selected: false,
    image: '1f343.png',
    code_decimal: '&#127811;',
    title: ':leaves:',
    description: 'LEAVES',
  },
  {
    type: 2,
    selected: false,
    image: '1f344.png',
    code_decimal: '&#127812;',
    title: ':mushroom:',
    description: 'MUSHROOM',
  },
  {
    type: 2,
    selected: false,
    image: '1f330.png',
    code_decimal: '&#127792;',
    title: ':chestnut:',
    description: 'CHESTNUT',
  },
  {
    type: 2,
    selected: false,
    image: '1f400.png',
    code_decimal: '&#128000;',
    title: ':rat:',
    description: 'RAT',
  },
  {
    type: 2,
    selected: false,
    image: '1f401.png',
    code_decimal: '&#128001;',
    title: ':mouse2:',
    description: 'MOUSE2',
  },
  {
    type: 2,
    selected: false,
    image: '1f42d.png',
    code_decimal: '&#128045;',
    title: ':mouse:',
    description: 'MOUSE',
  },
  {
    type: 2,
    selected: false,
    image: '1f439.png',
    code_decimal: '&#128057;',
    title: ':hamster:',
    description: 'HAMSTER',
  },
  {
    type: 2,
    selected: false,
    image: '1f402.png',
    code_decimal: '&#128002;',
    title: ':ox:',
    description: 'OX',
  },
  {
    type: 2,
    selected: false,
    image: '1f403.png',
    code_decimal: '&#128003;',
    title: ':water_buffalo:',
    description: 'WATER_BUFFALO',
  },
  {
    type: 2,
    selected: false,
    image: '1f404.png',
    code_decimal: '&#128004;',
    title: ':cow2:',
    description: 'COW2',
  },
  {
    type: 2,
    selected: false,
    image: '1f42e.png',
    code_decimal: '&#128046;',
    title: ':cow:',
    description: 'COW',
  },
  {
    type: 2,
    selected: false,
    image: '1f405.png',
    code_decimal: '&#128005;',
    title: ':tiger2:',
    description: 'TIGER2',
  },
  {
    type: 2,
    selected: false,
    image: '1f406.png',
    code_decimal: '&#128006;',
    title: ':leopard:',
    description: 'LEOPARD',
  },
  {
    type: 2,
    selected: false,
    image: '1f42f.png',
    code_decimal: '&#128047;',
    title: ':tiger:',
    description: 'TIGER',
  },
  {
    type: 2,
    selected: false,
    image: '1f43f.png',
    code_decimal: '&#128063;',
    title: ':chipmunk:',
    description: 'CHIPMUNK',
  },
  {
    type: 2,
    selected: false,
    image: '1f407.png',
    code_decimal: '&#128007;',
    title: ':rabbit2:',
    description: 'RABBIT2',
  },
  {
    type: 2,
    selected: false,
    image: '1f430.png',
    code_decimal: '&#128048;',
    title: ':rabbit:',
    description: 'RABBIT',
  },
  {
    type: 2,
    selected: false,
    image: '1f408.png',
    code_decimal: '&#128008;',
    title: ':cat2:',
    description: 'CAT2',
  },
  {
    type: 2,
    selected: false,
    image: '1f431.png',
    code_decimal: '&#128049;',
    title: ':cat:',
    description: 'CAT',
  },
  {
    type: 2,
    selected: false,
    image: '1f40e.png',
    code_decimal: '&#128014;',
    title: ':racehorse:',
    description: 'RACEHORSE',
  },
  {
    type: 2,
    selected: false,
    image: '1f434.png',
    code_decimal: '&#128052;',
    title: ':horse:',
    description: 'HORSE',
  },
  {
    type: 2,
    selected: false,
    image: '1f40f.png',
    code_decimal: '&#128015;',
    title: ':ram:',
    description: 'RAM',
  },
  {
    type: 2,
    selected: false,
    image: '1f411.png',
    code_decimal: '&#128017;',
    title: ':sheep:',
    description: 'SHEEP',
  },
  {
    type: 2,
    selected: false,
    image: '1f410.png',
    code_decimal: '&#128016;',
    title: ':goat:',
    description: 'GOAT',
  },
  {
    type: 2,
    selected: false,
    image: '1f413.png',
    code_decimal: '&#128019;',
    title: ':rooster:',
    description: 'ROOSTER',
  },
  {
    type: 2,
    selected: false,
    image: '1f414.png',
    code_decimal: '&#128020;',
    title: ':chicken:',
    description: 'CHICKEN',
  },
  {
    type: 2,
    selected: false,
    image: '1f424.png',
    code_decimal: '&#128036;',
    title: ':baby_chick:',
    description: 'BABY_CHICK',
  },
  {
    type: 2,
    selected: false,
    image: '1f423.png',
    code_decimal: '&#128035;',
    title: ':hatching_chick:',
    description: 'HATCHING_CHICK',
  },
  {
    type: 2,
    selected: false,
    image: '1f425.png',
    code_decimal: '&#128037;',
    title: ':hatched_chick:',
    description: 'HATCHED_CHICK',
  },
  {
    type: 2,
    selected: false,
    image: '1f426.png',
    code_decimal: '&#128038;',
    title: ':bird:',
    description: 'BIRD',
  },
  {
    type: 2,
    selected: false,
    image: '1f427.png',
    code_decimal: '&#128039;',
    title: ':penguin:',
    description: 'PENGUIN',
  },
  {
    type: 2,
    selected: false,
    image: '1f418.png',
    code_decimal: '&#128024;',
    title: ':elephant:',
    description: 'ELEPHANT',
  },
  {
    type: 2,
    selected: false,
    image: '1f42a.png',
    code_decimal: '&#128042;',
    title: ':dromedary_camel:',
    description: 'DROMEDARY_CAMEL',
  },
  {
    type: 2,
    selected: false,
    image: '1f42b.png',
    code_decimal: '&#128043;',
    title: ':camel:',
    description: 'CAMEL',
  },
  {
    type: 2,
    selected: false,
    image: '1f417.png',
    code_decimal: '&#128023;',
    title: ':boar:',
    description: 'BOAR',
  },
  {
    type: 2,
    selected: false,
    image: '1f416.png',
    code_decimal: '&#128022;',
    title: ':pig2:',
    description: 'PIG2',
  },
  {
    type: 2,
    selected: false,
    image: '1f437.png',
    code_decimal: '&#128055;',
    title: ':pig:',
    description: 'PIG',
  },
  {
    type: 2,
    selected: false,
    image: '1f43d.png',
    code_decimal: '&#128061;',
    title: ':pig_nose:',
    description: 'PIG_NOSE',
  },
  {
    type: 2,
    selected: false,
    image: '1f415.png',
    code_decimal: '&#128021;',
    title: ':dog2:',
    description: 'DOG2',
  },
  {
    type: 2,
    selected: false,
    image: '1f429.png',
    code_decimal: '&#128041;',
    title: ':poodle:',
    description: 'POODLE',
  },
  {
    type: 2,
    selected: false,
    image: '1f436.png',
    code_decimal: '&#128054;',
    title: ':dog:',
    description: 'DOG',
  },
  {
    type: 2,
    selected: false,
    image: '1f43a.png',
    code_decimal: '&#128058;',
    title: ':wolf:',
    description: 'WOLF',
  },
  {
    type: 2,
    selected: false,
    image: '1f43b.png',
    code_decimal: '&#128059;',
    title: ':bear:',
    description: 'BEAR',
  },
  {
    type: 2,
    selected: false,
    image: '1f428.png',
    code_decimal: '&#128040;',
    title: ':koala:',
    description: 'KOALA',
  },
  {
    type: 2,
    selected: false,
    image: '1f43c.png',
    code_decimal: '&#128060;',
    title: ':panda_face:',
    description: 'PANDA_FACE',
  },
  {
    type: 2,
    selected: false,
    image: '1f435.png',
    code_decimal: '&#128053;',
    title: ':monkey_face:',
    description: 'MONKEY_FACE',
  },
  {
    type: 2,
    selected: false,
    image: '1f648.png',
    code_decimal: '&#128584;',
    title: ':see_no_evil:',
    description: 'SEE_NO_EVIL',
  },
  {
    type: 2,
    selected: false,
    image: '1f649.png',
    code_decimal: '&#128585;',
    title: ':hear_no_evil:',
    description: 'HEAR_NO_EVIL',
  },
  {
    type: 2,
    selected: false,
    image: '1f64a.png',
    code_decimal: '&#128586;',
    title: ':speak_no_evil:',
    description: 'SPEAK_NO_EVIL',
  },
  {
    type: 2,
    selected: false,
    image: '1f412.png',
    code_decimal: '&#128018;',
    title: ':monkey:',
    description: 'MONKEY',
  },
  {
    type: 2,
    selected: false,
    image: '1f409.png',
    code_decimal: '&#128009;',
    title: ':dragon:',
    description: 'DRAGON',
  },
  {
    type: 2,
    selected: false,
    image: '1f432.png',
    code_decimal: '&#128050;',
    title: ':dragon_face:',
    description: 'DRAGON_FACE',
  },
  {
    type: 2,
    selected: false,
    image: '1f40a.png',
    code_decimal: '&#128010;',
    title: ':crocodile:',
    description: 'CROCODILE',
  },
  {
    type: 2,
    selected: false,
    image: '1f40d.png',
    code_decimal: '&#128013;',
    title: ':snake:',
    description: 'SNAKE',
  },
  {
    type: 2,
    selected: false,
    image: '1f422.png',
    code_decimal: '&#128034;',
    title: ':turtle:',
    description: 'TURTLE',
  },
  {
    type: 2,
    selected: false,
    image: '1f438.png',
    code_decimal: '&#128056;',
    title: ':frog:',
    description: 'FROG',
  },
  {
    type: 2,
    selected: false,
    image: '1f40b.png',
    code_decimal: '&#128011;',
    title: ':whale2:',
    description: 'WHALE2',
  },
  {
    type: 2,
    selected: false,
    image: '1f433.png',
    code_decimal: '&#128051;',
    title: ':whale:',
    description: 'WHALE',
  },
  {
    type: 2,
    selected: false,
    image: '1f42c.png',
    code_decimal: '&#128044;',
    title: ':dolphin:',
    description: 'DOLPHIN',
  },
  {
    type: 2,
    selected: false,
    image: '1f419.png',
    code_decimal: '&#128025;',
    title: ':octopus:',
    description: 'OCTOPUS',
  },
  {
    type: 2,
    selected: false,
    image: '1f41f.png',
    code_decimal: '&#128031;',
    title: ':fish:',
    description: 'FISH',
  },
  {
    type: 2,
    selected: false,
    image: '1f420.png',
    code_decimal: '&#128032;',
    title: ':tropical_fish:',
    description: 'TROPICAL_FISH',
  },
  {
    type: 2,
    selected: false,
    image: '1f421.png',
    code_decimal: '&#128033;',
    title: ':blowfish:',
    description: 'BLOWFISH',
  },
  {
    type: 2,
    selected: false,
    image: '1f41a.png',
    code_decimal: '&#128026;',
    title: ':shell:',
    description: 'SHELL',
  },
  {
    type: 2,
    selected: false,
    image: '1f40c.png',
    code_decimal: '&#128012;',
    title: ':snail:',
    description: 'SNAIL',
  },
  {
    type: 2,
    selected: false,
    image: '1f41b.png',
    code_decimal: '&#128027;',
    title: ':bug:',
    description: 'BUG',
  },
  {
    type: 2,
    selected: false,
    image: '1f41c.png',
    code_decimal: '&#128028;',
    title: ':ant:',
    description: 'ANT',
  },
  {
    type: 2,
    selected: false,
    image: '1f41d.png',
    code_decimal: '&#128029;',
    title: ':bee:',
    description: 'BEE',
  },
  {
    type: 2,
    selected: false,
    image: '1f41e.png',
    code_decimal: '&#128030;',
    title: ':beetle:',
    description: 'BEETLE',
  },
  {
    type: 2,
    selected: false,
    image: '1f577.png',
    code_decimal: '&#128375;',
    title: ':spider:',
    description: 'SPIDER',
  },
  {
    type: 2,
    selected: false,
    image: '1f578.png',
    code_decimal: '&#128376;',
    title: ':spider_web:',
    description: 'SPIDER_WEB',
  },
  {
    type: 2,
    selected: false,
    image: '1f43e.png',
    code_decimal: '&#128062;',
    title: ':feet:',
    description: 'FEET',
  },
  {
    type: 2,
    selected: false,
    image: '26a1.png',
    code_decimal: '&#9889;',
    title: ':zap:',
    description: 'ZAP',
  },
  {
    type: 2,
    selected: false,
    image: '1f525.png',
    code_decimal: '&#128293;',
    title: ':fire:',
    description: 'FIRE',
  },
  {
    type: 2,
    selected: false,
    image: '1f319.png',
    code_decimal: '&#127769;',
    title: ':crescent_moon:',
    description: 'CRESCENT_MOON',
  },
  {
    type: 2,
    selected: false,
    image: '2600.png',
    code_decimal: '&#9728;',
    title: ':sunny:',
    description: 'SUNNY',
  },
  {
    type: 2,
    selected: false,
    image: '26c5.png',
    code_decimal: '&#9925;',
    title: ':partly_sunny:',
    description: 'PARTLY_SUNNY',
  },
  {
    type: 2,
    selected: false,
    image: '2601.png',
    code_decimal: '&#9729;',
    title: ':cloud:',
    description: 'CLOUD',
  },
  {
    type: 2,
    selected: false,
    image: '1f327.png',
    code_decimal: '&#127783;',
    title: ':cloud_rain:',
    description: 'CLOUD_RAIN',
  },
  {
    type: 2,
    selected: false,
    image: '1f328.png',
    code_decimal: '&#127784;',
    title: ':cloud_snow:',
    description: 'CLOUD_SNOW',
  },
  {
    type: 2,
    selected: false,
    image: '1f329.png',
    code_decimal: '&#127785;',
    title: ':cloud_lightning:',
    description: 'CLOUD_LIGHTNING',
  },
  {
    type: 2,
    selected: false,
    image: '1f32a.png',
    code_decimal: '&#127786;',
    title: ':cloud_tornado:',
    description: 'CLOUD_TORNADO',
  },
  {
    type: 2,
    selected: false,
    image: '1f4a7.png',
    code_decimal: '&#128167;',
    title: ':droplet:',
    description: 'DROPLET',
  },
  {
    type: 2,
    selected: false,
    image: '1f4a6.png',
    code_decimal: '&#128166;',
    title: ':sweat_drops:',
    description: 'SWEAT_DROPS',
  },
  {
    type: 2,
    selected: false,
    image: '2614.png',
    code_decimal: '&#9748;',
    title: ':umbrella:',
    description: 'UMBRELLA',
  },
  {
    type: 2,
    selected: false,
    image: '1f32b.png',
    code_decimal: '&#127787;',
    title: ':fog:',
    description: 'FOG',
  },
  {
    type: 2,
    selected: false,
    image: '1f4a8.png',
    code_decimal: '&#128168;',
    title: ':dash:',
    description: 'DASH',
  },
  {
    type: 2,
    selected: false,
    image: '2744.png',
    code_decimal: '&#10052;',
    title: ':snowflake:',
    description: 'SNOWFLAKE',
  },
  {
    type: 2,
    selected: false,
    image: '1f31f.png',
    code_decimal: '&#127775;',
    title: ':star2:',
    description: 'STAR2',
  },
  {
    type: 2,
    selected: false,
    image: '2b50.png',
    code_decimal: '&#11088;',
    title: ':star:',
    description: 'STAR',
  },
  {
    type: 2,
    selected: false,
    image: '1f320.png',
    code_decimal: '&#127776;',
    title: ':stars:',
    description: 'STARS',
  },
  {
    type: 2,
    selected: false,
    image: '1f304.png',
    code_decimal: '&#127748;',
    title: ':sunrise_over_mountains:',
    description: 'SUNRISE_OVER_MOUNTAINS',
  },
  {
    type: 2,
    selected: false,
    image: '1f305.png',
    code_decimal: '&#127749;',
    title: ':sunrise:',
    description: 'SUNRISE',
  },
  {
    type: 2,
    selected: false,
    image: '1f308.png',
    code_decimal: '&#127752;',
    title: ':rainbow:',
    description: 'RAINBOW',
  },
  {
    type: 2,
    selected: false,
    image: '1f30a.png',
    code_decimal: '&#127754;',
    title: ':ocean:',
    description: 'OCEAN',
  },
  {
    type: 2,
    selected: false,
    image: '1f30b.png',
    code_decimal: '&#127755;',
    title: ':volcano:',
    description: 'VOLCANO',
  },
  {
    type: 2,
    selected: false,
    image: '1f30c.png',
    code_decimal: '&#127756;',
    title: ':milky_way:',
    description: 'MILKY_WAY',
  },
  {
    type: 2,
    selected: false,
    image: '1f5fb.png',
    code_decimal: '&#128507;',
    title: ':mount_fuji:',
    description: 'MOUNT_FUJI',
  },
  {
    type: 2,
    selected: false,
    image: '1f5fe.png',
    code_decimal: '&#128510;',
    title: ':japan:',
    description: 'JAPAN',
  },
  {
    type: 2,
    selected: false,
    image: '1f310.png',
    code_decimal: '&#127760;',
    title: ':globe_with_meridians:',
    description: 'GLOBE_WITH_MERIDIANS',
  },
  {
    type: 2,
    selected: false,
    image: '1f30d.png',
    code_decimal: '&#127757;',
    title: ':earth_africa:',
    description: 'EARTH_AFRICA',
  },
  {
    type: 2,
    selected: false,
    image: '1f30e.png',
    code_decimal: '&#127758;',
    title: ':earth_americas:',
    description: 'EARTH_AMERICAS',
  },
  {
    type: 2,
    selected: false,
    image: '1f30f.png',
    code_decimal: '&#127759;',
    title: ':earth_asia:',
    description: 'EARTH_ASIA',
  },
  {
    type: 2,
    selected: false,
    image: '1f311.png',
    code_decimal: '&#127761;',
    title: ':new_moon:',
    description: 'NEW_MOON',
  },
  {
    type: 2,
    selected: false,
    image: '1f312.png',
    code_decimal: '&#127762;',
    title: ':waxing_crescent_moon:',
    description: 'WAXING_CRESCENT_MOON',
  },
  {
    type: 2,
    selected: false,
    image: '1f313.png',
    code_decimal: '&#127763;',
    title: ':first_quarter_moon:',
    description: 'FIRST_QUARTER_MOON',
  },
  {
    type: 2,
    selected: false,
    image: '1f314.png',
    code_decimal: '&#127764;',
    title: ':waxing_gibbous_moon:',
    description: 'WAXING_GIBBOUS_MOON',
  },
  {
    type: 2,
    selected: false,
    image: '1f315.png',
    code_decimal: '&#127765;',
    title: ':full_moon:',
    description: 'FULL_MOON',
  },
  {
    type: 2,
    selected: false,
    image: '1f316.png',
    code_decimal: '&#127766;',
    title: ':waning_gibbous_moon:',
    description: 'WANING_GIBBOUS_MOON',
  },
  {
    type: 2,
    selected: false,
    image: '1f317.png',
    code_decimal: '&#127767;',
    title: ':last_quarter_moon:',
    description: 'LAST_QUARTER_MOON',
  },
  {
    type: 2,
    selected: false,
    image: '1f318.png',
    code_decimal: '&#127768;',
    title: ':waning_crescent_moon:',
    description: 'WANING_CRESCENT_MOON',
  },
  {
    type: 2,
    selected: false,
    image: '1f31a.png',
    code_decimal: '&#127770;',
    title: ':new_moon_with_face:',
    description: 'NEW_MOON_WITH_FACE',
  },
  {
    type: 2,
    selected: false,
    image: '1f31d.png',
    code_decimal: '&#127773;',
    title: ':full_moon_with_face:',
    description: 'FULL_MOON_WITH_FACE',
  },
  {
    type: 2,
    selected: false,
    image: '1f31b.png',
    code_decimal: '&#127771;',
    title: ':first_quarter_moon_with_face:',
    description: 'FIRST_QUARTER_MOON_WITH_FACE',
  },
  {
    type: 2,
    selected: false,
    image: '1f31c.png',
    code_decimal: '&#127772;',
    title: ':last_quarter_moon_with_face:',
    description: 'LAST_QUARTER_MOON_WITH_FACE',
  },
  {
    type: 2,
    selected: false,
    image: '1f31e.png',
    code_decimal: '&#127774;',
    title: ':sun_with_face:',
    description: 'SUN_WITH_FACE',
  },
  {
    type: 2,
    selected: false,
    image: '1f32c.png',
    code_decimal: '&#127788;',
    title: ':wind_blowing_face:',
    description: 'WIND_BLOWING_FACE',
  },
];
export default jsonEmoji2;
